To run this, press "*Runtime*" and press "*Run all*" on a **free** Tesla T4 Google Colab instance!
<div class="align-center">
<a href="https://unsloth.ai/"><img src="https://github.com/unslothai/unsloth/raw/main/images/unsloth%20new%20logo.png" width="115"></a>
<a href="https://discord.gg/unsloth"><img src="https://github.com/unslothai/unsloth/raw/main/images/Discord button.png" width="145"></a>
<a href="https://unsloth.ai/docs/"><img src="https://github.com/unslothai/unsloth/blob/main/images/documentation%20green%20button.png?raw=true" width="125"></a> Join Discord if you need help + ⭐ <i>Star us on <a href="https://github.com/unslothai/unsloth">Github</a> </i> ⭐
</div>

To install Unsloth on your local device, follow [our guide](https://unsloth.ai/docs/get-started/install). This notebook is licensed [LGPL-3.0](https://github.com/unslothai/notebooks?tab=LGPL-3.0-1-ov-file#readme).

You will learn how to do [data prep](#Data), how to [train](#Train), how to [run the model](#Inference), & how to save it

### News

Train MoEs - DeepSeek, GLM, Qwen and gpt-oss 12x faster with 35% less VRAM. [Blog](https://unsloth.ai/docs/new/faster-moe)

You can now train embedding models 1.8-3.3x faster with 20% less VRAM. [Blog](https://unsloth.ai/docs/new/embedding-finetuning)

Ultra Long-Context Reinforcement Learning is here with 7x more context windows! [Blog](https://unsloth.ai/docs/new/grpo-long-context)

3x faster LLM training with 30% less VRAM and 500K context. [3x faster](https://unsloth.ai/docs/new/3x-faster-training-packing) • [500K Context](https://unsloth.ai/docs/new/500k-context-length-fine-tuning)

New in Reinforcement Learning: [FP8 RL](https://unsloth.ai/docs/new/fp8-reinforcement-learning) • [Vision RL](https://unsloth.ai/docs/new/vision-reinforcement-learning-vlm-rl) • [Standby](https://unsloth.ai/docs/basics/memory-efficient-rl) • [gpt-oss RL](https://unsloth.ai/docs/new/gpt-oss-reinforcement-learning)

Visit our docs for all our [model uploads](https://unsloth.ai/docs/get-started/unsloth-model-catalog) and [notebooks](https://unsloth.ai/docs/get-started/unsloth-notebooks).

### Installation

In [22]:
# %%capture
# import os, re
# if "COLAB_" not in "".join(os.environ.keys()):
#   !uv add unsloth # Do this in local & cloud setups
# else:
#   import torch; v = re.match(r'[\d]{1,}\.[\d]{1,}', str(torch.__version__)).group(0)
#   xformers = 'xformers==' + {'2.10':'0.0.34','2.9':'0.0.33.post1','2.8':'0.0.32.post2'}.get(v, "0.0.34")
#   !uv add sentencepiece protobuf "datasets==4.3.0" "huggingface_hub>=0.34.0" hf_transfer
#   !uv add unsloth_zoo bitsandbytes accelerate {xformers} peft trl triton unsloth
# !uv add transformers==4.56.2
# !uv add trl==0.22.2

### Unsloth

`FastModel` supports loading nearly any model now! This includes Vision and Text models!

In [2]:
from unsloth import FastModel
import torch

fourbit_models = [
  # 4bit dynamic quants for superior accuracy and low memory use
  "unsloth/gemma-3-1b-it-unsloth-bnb-4bit",
  "unsloth/gemma-3-4b-it-unsloth-bnb-4bit",
  "unsloth/gemma-3-12b-it-unsloth-bnb-4bit",
  "unsloth/gemma-3-27b-it-unsloth-bnb-4bit",

  # Other popular models!
  "unsloth/Llama-3.1-8B",
  "unsloth/Llama-3.2-3B",
  "unsloth/Llama-3.3-70B",
  "unsloth/mistral-7b-instruct-v0.3",
  "unsloth/Phi-4",
] # More models at https://huggingface.co/unsloth

model, tokenizer = FastModel.from_pretrained(
  model_name = "unsloth/gemma-3-4b-it",
  max_seq_length = 2048, # Choose any for long context!
  load_in_4bit = True, # 4 bit quantization to reduce memory
  load_in_8bit = False, # [NEW!] A bit more accurate, uses 2x memory
  full_finetuning = False, # [NEW!] We have full finetuning now!
  # token = "YOUR_HF_TOKEN", # HF Token for gated models
)

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.

/home/wa1ter/ESG-sft/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

🦥 Unsloth Zoo will now patch everything to make training faster!
==((====))==  Unsloth 2026.3.4: Fast Gemma3 patching. Transformers: 5.2.0.
   \\   /|    NVIDIA GeForce RTX 4090. Num GPUs = 1. Max memory: 23.518 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.9.1+cu128. CUDA: 8.9. CUDA Toolkit: 12.8. Triton: 3.5.1
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.33.post2. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Loading weights: 100%|██████████| 883/883 [00:01<00:00, 871.07it/s, Materializing param=model.vision_tower.vision_model.post_layernorm.weight]
The image processor of type `Gemma3ImageProcessor` is now loaded as a fast processor by default, even if the model checkpoint was saved with a slow processor. This is a breaking change and may produce slightly different outputs. To continue using the slow processor, instantiate this class with `use_fast=False`.

Skipping model.language_model.layers.0.mlp.gate_proj: no quant_state found
Skipping model.language_model.layers.0.mlp.up_proj: no quant_state found
Skipping model.language_model.layers.0.mlp.down_proj: no quant_state found
Skipping model.language_model.layers.1.mlp.gate_proj: no quant_state found
Skipping model.language_model.layers.1.mlp.up_proj: no quant_state found
Skipping model.language_model.layers.1.mlp.down_proj: no quant_state found
Skipping model.language_model.layers.2.self_attn.q_proj: no quant_state found
Skipping model.language_model.layers.2.self_attn.k_proj: no quant_state found
Skipping model.language_model.layers.2.self_attn.v_proj: no quant_state found
Skipping model.language_model.layers.2.self_attn.o_proj: no quant_state found
Skipping model.language_model.layers.2.mlp.gate_proj: no quant_state found
Skipping model.language_model.layers.2.mlp.up_proj: no quant_state found
Skipping model.language_model.layers.2.mlp.down_proj: no quant_state found
Skipping model.language_model.layers.3.mlp.gate_proj: no quant_state found
Skipping model.language_model.layers.3.mlp.up_proj: no quant_state found
Skipping model.language_model.layers.3.mlp.down_proj: no quant_state found
Skipping model.language_model.layers.4.mlp.gate_proj: no quant_state found
Skipping model.language_model.layers.4.mlp.up_proj: no quant_state found
Skipping model.language_model.layers.4.mlp.down_proj: no quant_state found
Skipping model.language_model.layers.5.mlp.gate_proj: no quant_state found
Skipping model.language_model.layers.5.mlp.up_proj: no quant_state found
Skipping model.language_model.layers.5.mlp.down_proj: no quant_state found

We now add LoRA adapters so we only need to update a small amount of parameters!

In [3]:
model = FastModel.get_peft_model(
  model,
  finetune_vision_layers   = False, # Turn off for just text!
  finetune_language_layers  = True, # Should leave on!
  finetune_attention_modules = True, # Attention good for GRPO
  finetune_mlp_modules    = True, # Should leave on always!

  r = 16,      # Larger = higher accuracy, but might overfit
  lora_alpha = 16, # Recommended alpha == r at least
  lora_dropout = 0,
  bias = "none",
  random_state = 3407,
)

Unsloth: Making `model.base_model.model.model.language_model` require gradients

<a name="Data"></a>
### Data Prep
We now use the `Gemma-3` format for conversation style finetunes. We use [Maxime Labonne's FineTome-100k](https://huggingface.co/datasets/mlabonne/FineTome-100k) dataset in ShareGPT style. Gemma-3 renders multi turn conversations like below:

```
<bos><start_of_turn>user
Hello!<end_of_turn>
<start_of_turn>model
Hey there!<end_of_turn>
```

We use our `get_chat_template` function to get the correct chat template. We support `zephyr, chatml, mistral, llama, alpaca, vicuna, vicuna_old, phi3, llama3, phi4, qwen2.5, gemma3` and more.

In [4]:
from unsloth.chat_templates import get_chat_template
tokenizer = get_chat_template(
  tokenizer,
  chat_template = "gemma-3",
)

In [5]:
from datasets import load_dataset
# dataset = load_dataset("mlabonne/FineTome-100k", split = "train")
dataset_train = load_dataset("json", data_files="../../data/processed/step6_sft/train_sft_xml.json", split="train")
# dataset_val = load_dataset("json", data_files="../data/fine-tuning_data/test.json", split="train")

Generating train split: 779 examples [00:00, 33602.74 examples/s]

We now use `standardize_data_formats` to try converting datasets to the correct format for finetuning purposes!

In [6]:
from unsloth.chat_templates import standardize_data_formats
dataset = standardize_data_formats(dataset_train)
# dataset_val = standardize_data_formats(dataset_val)

Unsloth: Standardizing formats (num_proc=36): 100%|██████████| 779/779 [00:00<00:00, 945.40 examples/s]

Let's see how row 100 looks like!

In [7]:
dataset[10]
# dataset_val[10]

{'conversations': [{'content': 'You are an ESG (Environmental, Social, and Governance) risk classification expert specialized in analyzing U.S. 10-K filings. Your task is to classify paragraphs from Item 1A (Risk Factors) sections into exactly one of the following 9 categories.\n\nValid category names:\n- Climate Change\n- Natural Capital\n- Pollution & Waste\n- Human Capital\n- Product Liability\n- Community Relations\n- Corporate Governance\n- Business Ethics & Values\n- Non-ESG',
   'role': 'system'},
  {'content': "Classify the following paragraph from a 10-K filing into one of the 9 ESG categories based on the definitions below.\n\n=== CATEGORY DEFINITIONS ===\nClimate Change: This topic includes discussions about carbon emissions or climate change, including initiatives to increase carbon efficiency, environmental technologies, renewable energy, and the development or refurbishment of buildings with leading ecological design features. The following are some examples:\n- We are also excited about our commitment to securing 100% of our purchased electricity from renewable sources by 2025, reducing our operational carbon footprint by 30%.\n- In 2018, we acquired a 43.83% interest in Silicon Ranch, a leading US developer, owner, and operator of solar assets.\n- Beginning in 2012 through the end of 2016, we have converted 19 plants from coal to natural gas or steam.\n- 40% of our operations are to be certified under a green building standard by 2018.\n\nNatural Capital: This topic includes discussions about water stress, biodiversity, land use, and raw materials sourcing. For water stress, we include discussions of how companies manage risks of water shortages, such as by employing efficient water processes, water recycling, and alternative water sources. For biodiversity and land use, we include discussions about programs and policies designed to protect biodiversity and address community land-use concerns. For raw materials sourcing, we include discussions about policies and procedures to source materials with lower environmental impact, such as seafood/aquaculture, timber/paper, palm oil, beef/dairy, leather, and cotton.\n\nPollution & Waste: This topic includes discussions about toxic emissions, packaging materials, and electronic waste. For toxic emissions and waste, we include discussions of pollution, contamination, and emission of toxic and carcinogenic substances and wastewater. For packaging materials and waste, we include discussions of product packaging content and end-of-life recycling or disposal of packaging materials. We include discussions about the recycling and removal of end-of-life electronic products for electronic waste.\n\nHuman Capital: This topic includes discussions about labor management, health and safety, human capital development and training, and supply chain labor standards. For labor management, we include discussions workforce management, risk of workflow disruptions, labor productivity issues, employee diversity, and pay equality (non-executive). For health and safety, we include discussions of employee health and safety (H&S) programs. For human capital development and training, we include discussions of the ability to attract, retain, and develop human capital based on benefits, training, development programs, and employee engagement provided. For supply chain labor standards, we include discussions of supply chain production disruptions and brand value damage due to sub-standard treatment of workers.\n\nProduct Liability: This topic includes discussing product safety and quality, privacy and data security, chemical safety, consumer financial protection, and health and demographic risk. For product safety and quality, we include discussion of product recalls, losing customer trust through product quality concerns. For privacy and data security, we have discussions of data security breaches, the controversial use of personal data. For chemical safety, we include discussions of the use or presence of chemicals of concern. For consumer financial protection, we include discussions of the transparency of financial products. For health and demographic risk, we include discussions of public health trends.\n\nCommunity Relations: This topic includes discussions of a firm's interaction with its local communities, including access to communications, access to finance, and access to healthcare. We include discussions about opportunities in historically underserved markets, such as developing countries and underserved populations, and relevant philanthropic efforts.\n\nCorporate Governance: This topic includes discussions on shareholders and ownership, board of directors, executive pay, and internal controls. For shareholders and ownership, we include discussions regarding ownership structure, control structure, and shareholders. For the board of directors, we include discussions of the board's independence from management, board skills and diversity, and board effectiveness. For executive pay, we include CEO and other executives' pay practices. For internal control, we consider internal controls, audit matters, and internal audit matters.\n\nBusiness Ethics & Values: This topic includes discussions about ethical components such as a firm's values and controversies. We include discussions about the ethical conduct of business, fraud, corruption, bribery, fiduciary responsibilities, conflicts of interest, misrepresentation, bias, negligence, political contributions, negative accounting events, and other behaviors which may have ethical components.\n\nNon-ESG: The paragraph does not primarily discuss any of the above ESG topics. Typical Non-ESG content includes: general financial performance, revenue/earnings discussions, market competition, product/service descriptions, operational logistics, legal boilerplate, accounting policies, and general business strategy unrelated to ESG.\n\n=== IMPORTANT RULES ===\n- Choose the SINGLE most relevant category.\n- Only classify as an ESG category if the paragraph PRIMARILY discusses that topic.\n- If uncertain between an ESG category and Non-ESG, lean toward Non-ESG.\n\n=== PARAGRAPH TO CLASSIFY ===\nRisks related to our business and industry\nWe may not be able to successfully open new store locations in a timely manner, if at all, which could harm our results of operations.",
   'role': 'user'},
  {'content': '<reasoning>\nKey keywords/concepts in the paragraph include "open new store locations," "timely manner," and "harm our results of operations," which relate to operational expansion and business performance. These concepts map to Non-ESG because they describe general business risk about store openings and financial/operational outcomes rather than environmental, social, or governance issues defined by the ESG categories. The paragraph does not discuss climate, natural resources, pollution, workforce or labor practices, product safety, community engagement, governance, or ethics, so none of the ESG categories apply.\n</reasoning>\n<label>Non-ESG</label>',
   'role': 'assistant'}]}

We now have to apply the chat template for `Gemma-3` onto the conversations, and save it to `text`. We remove the `<bos>` token using removeprefix(`'<bos>'`) since we're finetuning. The Processor will add this token before training and the model expects only one.

In [8]:
def formatting_prompts_func(examples):
  convos = examples["conversations"]
  texts = [tokenizer.apply_chat_template(convo, tokenize = False, add_generation_prompt = False).removeprefix('<bos>') for convo in convos]
  return { "text" : texts, }

dataset = dataset.map(formatting_prompts_func, batched = True)

Map: 100%|██████████| 779/779 [00:00<00:00, 15090.70 examples/s]

Let's see how the chat template did! Notice there is no `<bos>` token as the processor tokenizer will be adding one.

In [9]:
dataset[100]["text"]

'<start_of_turn>user\nYou are an ESG (Environmental, Social, and Governance) risk classification expert specialized in analyzing U.S. 10-K filings. Your task is to classify paragraphs from Item 1A (Risk Factors) sections into exactly one of the following 9 categories.\n\nValid category names:\n- Climate Change\n- Natural Capital\n- Pollution & Waste\n- Human Capital\n- Product Liability\n- Community Relations\n- Corporate Governance\n- Business Ethics & Values\n- Non-ESG\n\nClassify the following paragraph from a 10-K filing into one of the 9 ESG categories based on the definitions below.\n\n=== CATEGORY DEFINITIONS ===\nClimate Change: This topic includes discussions about carbon emissions or climate change, including initiatives to increase carbon efficiency, environmental technologies, renewable energy, and the development or refurbishment of buildings with leading ecological design features. The following are some examples:\n- We are also excited about our commitment to securing 100% of our purchased electricity from renewable sources by 2025, reducing our operational carbon footprint by 30%.\n- In 2018, we acquired a 43.83% interest in Silicon Ranch, a leading US developer, owner, and operator of solar assets.\n- Beginning in 2012 through the end of 2016, we have converted 19 plants from coal to natural gas or steam.\n- 40% of our operations are to be certified under a green building standard by 2018.\n\nNatural Capital: This topic includes discussions about water stress, biodiversity, land use, and raw materials sourcing. For water stress, we include discussions of how companies manage risks of water shortages, such as by employing efficient water processes, water recycling, and alternative water sources. For biodiversity and land use, we include discussions about programs and policies designed to protect biodiversity and address community land-use concerns. For raw materials sourcing, we include discussions about policies and procedures to source materials with lower environmental impact, such as seafood/aquaculture, timber/paper, palm oil, beef/dairy, leather, and cotton.\n\nPollution & Waste: This topic includes discussions about toxic emissions, packaging materials, and electronic waste. For toxic emissions and waste, we include discussions of pollution, contamination, and emission of toxic and carcinogenic substances and wastewater. For packaging materials and waste, we include discussions of product packaging content and end-of-life recycling or disposal of packaging materials. We include discussions about the recycling and removal of end-of-life electronic products for electronic waste.\n\nHuman Capital: This topic includes discussions about labor management, health and safety, human capital development and training, and supply chain labor standards. For labor management, we include discussions workforce management, risk of workflow disruptions, labor productivity issues, employee diversity, and pay equality (non-executive). For health and safety, we include discussions of employee health and safety (H&S) programs. For human capital development and training, we include discussions of the ability to attract, retain, and develop human capital based on benefits, training, development programs, and employee engagement provided. For supply chain labor standards, we include discussions of supply chain production disruptions and brand value damage due to sub-standard treatment of workers.\n\nProduct Liability: This topic includes discussing product safety and quality, privacy and data security, chemical safety, consumer financial protection, and health and demographic risk. For product safety and quality, we include discussion of product recalls, losing customer trust through product quality concerns. For privacy and data security, we have discussions of data security breaches, the controversial use of personal data. For chemical safety, we include discussions of the use or presence of chemicals of concern. For consumer financial protection, we include discussions of the transparency of financial products. For health and demographic risk, we include discussions of public health trends.\n\nCommunity Relations: This topic includes discussions of a firm\'s interaction with its local communities, including access to communications, access to finance, and access to healthcare. We include discussions about opportunities in historically underserved markets, such as developing countries and underserved populations, and relevant philanthropic efforts.\n\nCorporate Governance: This topic includes discussions on shareholders and ownership, board of directors, executive pay, and internal controls. For shareholders and ownership, we include discussions regarding ownership structure, control structure, and shareholders. For the board of directors, we include discussions of the board\'s independence from management, board skills and diversity, and board effectiveness. For executive pay, we include CEO and other executives\' pay practices. For internal control, we consider internal controls, audit matters, and internal audit matters.\n\nBusiness Ethics & Values: This topic includes discussions about ethical components such as a firm\'s values and controversies. We include discussions about the ethical conduct of business, fraud, corruption, bribery, fiduciary responsibilities, conflicts of interest, misrepresentation, bias, negligence, political contributions, negative accounting events, and other behaviors which may have ethical components.\n\nNon-ESG: The paragraph does not primarily discuss any of the above ESG topics. Typical Non-ESG content includes: general financial performance, revenue/earnings discussions, market competition, product/service descriptions, operational logistics, legal boilerplate, accounting policies, and general business strategy unrelated to ESG.\n\n=== IMPORTANT RULES ===\n- Choose the SINGLE most relevant category.\n- Only classify as an ESG category if the paragraph PRIMARILY discusses that topic.\n- If uncertain between an ESG category and Non-ESG, lean toward Non-ESG.\n\n=== PARAGRAPH TO CLASSIFY ===\nBUSINESS AND OPERATIONAL RISK FACTORS\nThe single largest variable that affects the company’s results of operations is the price of crude oil, which can be influenced by general economic conditions, industry production and inventory levels, technology advancements, production quotas or other actions that might be imposed by the Organization of Petroleum Exporting Countries or other producers, weather-related damage and disruptions due to other natural or human causes beyond our control (including without limitation due to the COVID-19 pandemic), competing fuel prices, geopolitical risks, the pace of energy transition, and governmental regulations and policies regarding the development of oil and gas reserves. Chevron evaluates the risk of changing commodity prices as a core part of its business planning process. An investment in the company carries significant exposure to fluctuations in global crude oil prices. Extended periods of low prices for crude oil can have a material adverse impact on the company’s results of operations, financial condition and liquidity. Among other things, the company’s upstream earnings, cash flows, and capital and exploratory expenditure programs could be negatively affected, as could its production and proved reserves. Upstream assets may also become impaired. Downstream earnings could be negatively affected because they depend upon the supply and demand for refined products and the associated margins on refined product sales. A significant or sustained decline in liquidity could adversely affect the company’s credit ratings, potentially increase financing costs and reduce access to capital markets. The company may be unable to realize anticipated cost savings, expenditure reductions and asset sales that are intended to compensate for such downturns, and such downturns may also slow the pace and scale at which we are able to invest in new business lines such as the lower carbon businesses associated with our Chevron New Energies organization.<end_of_turn>\n<start_of_turn>model\n<reasoning>\nKey keywords and concepts in the paragraph include crude oil prices, commodity price fluctuations, production, reserves, upstream/downstream earnings, cash flows, capital and exploratory expenditures, asset impairment, liquidity, credit ratings, and investment in lower carbon businesses as a business impact. These concepts map to Non-ESG because the paragraph discusses financial and operational risks tied to market prices, production and investment impacts rather than policies or practices addressing ESG topics (it frames energy transition and regulations as market drivers affecting financial performance rather than as environmental strategy or emissions commitments). While it mentions "pace of energy transition" and "lower carbon businesses," those references are contextual drivers of financial risk, not substantive climate initiatives or sustainability programs, so Climate Change and other environmental categories do not apply.\n</reasoning>\n<label>Non-ESG</label><end_of_turn>\n'

<a name="Train"></a>
### Train the model
Now let's train our model. We do 60 steps to speed things up, but you can set `num_train_epochs=1` for a full run, and turn off `max_steps=None`.

In [10]:
from trl import SFTTrainer, SFTConfig
trainer = SFTTrainer(
  model = model,
  tokenizer = tokenizer,
  train_dataset = dataset,
  eval_dataset = None, # Can set up evaluation!
  args = SFTConfig(
    dataset_text_field = "text",
    per_device_train_batch_size = 2,
    gradient_accumulation_steps = 4, # Use GA to mimic batch size!
    warmup_steps = 5,
    num_train_epochs = 1, # Set this for 1 full training run.
    # max_steps =200,
    learning_rate = 2e-4, # Reduce to 2e-5 for long training runs
    logging_steps = 1,
    optim = "adamw_8bit",
    weight_decay = 0.001,
    lr_scheduler_type = "linear",
    seed = 3407,
    report_to = "none", # Use TrackIO/WandB etc
  ),
)

We also use Unsloth's `train_on_completions` method to only train on the assistant outputs and ignore the loss on the user's inputs. This helps increase accuracy of finetunes!

In [11]:
from unsloth.chat_templates import train_on_responses_only
trainer = train_on_responses_only(
  trainer,
  instruction_part = "<start_of_turn>user\n",
  response_part = "<start_of_turn>model\n",
)

Map (num_proc=36): 100%|██████████| 779/779 [01:01<00:00, 12.73 examples/s]
Map (num_proc=36): 100%|██████████| 779/779 [00:00<00:00, 877.79 examples/s]
Filter (num_proc=36): 100%|██████████| 779/779 [00:00<00:00, 867.44 examples/s]

Let's verify masking the instruction part is done! Let's print the 100th row again. Notice how the sample only has a single `<bos>` as expected!

In [12]:
tokenizer.decode(trainer.train_dataset[100]["input_ids"])

'<bos><start_of_turn>user\nYou are an ESG (Environmental, Social, and Governance) risk classification expert specialized in analyzing U.S. 10-K filings. Your task is to classify paragraphs from Item 1A (Risk Factors) sections into exactly one of the following 9 categories.\n\nValid category names:\n- Climate Change\n- Natural Capital\n- Pollution & Waste\n- Human Capital\n- Product Liability\n- Community Relations\n- Corporate Governance\n- Business Ethics & Values\n- Non-ESG\n\nClassify the following paragraph from a 10-K filing into one of the 9 ESG categories based on the definitions below.\n\n=== CATEGORY DEFINITIONS ===\nClimate Change: This topic includes discussions about carbon emissions or climate change, including initiatives to increase carbon efficiency, environmental technologies, renewable energy, and the development or refurbishment of buildings with leading ecological design features. The following are some examples:\n- We are also excited about our commitment to securing 100% of our purchased electricity from renewable sources by 2025, reducing our operational carbon footprint by 30%.\n- In 2018, we acquired a 43.83% interest in Silicon Ranch, a leading US developer, owner, and operator of solar assets.\n- Beginning in 2012 through the end of 2016, we have converted 19 plants from coal to natural gas or steam.\n- 40% of our operations are to be certified under a green building standard by 2018.\n\nNatural Capital: This topic includes discussions about water stress, biodiversity, land use, and raw materials sourcing. For water stress, we include discussions of how companies manage risks of water shortages, such as by employing efficient water processes, water recycling, and alternative water sources. For biodiversity and land use, we include discussions about programs and policies designed to protect biodiversity and address community land-use concerns. For raw materials sourcing, we include discussions about policies and procedures to source materials with lower environmental impact, such as seafood/aquaculture, timber/paper, palm oil, beef/dairy, leather, and cotton.\n\nPollution & Waste: This topic includes discussions about toxic emissions, packaging materials, and electronic waste. For toxic emissions and waste, we include discussions of pollution, contamination, and emission of toxic and carcinogenic substances and wastewater. For packaging materials and waste, we include discussions of product packaging content and end-of-life recycling or disposal of packaging materials. We include discussions about the recycling and removal of end-of-life electronic products for electronic waste.\n\nHuman Capital: This topic includes discussions about labor management, health and safety, human capital development and training, and supply chain labor standards. For labor management, we include discussions workforce management, risk of workflow disruptions, labor productivity issues, employee diversity, and pay equality (non-executive). For health and safety, we include discussions of employee health and safety (H&S) programs. For human capital development and training, we include discussions of the ability to attract, retain, and develop human capital based on benefits, training, development programs, and employee engagement provided. For supply chain labor standards, we include discussions of supply chain production disruptions and brand value damage due to sub-standard treatment of workers.\n\nProduct Liability: This topic includes discussing product safety and quality, privacy and data security, chemical safety, consumer financial protection, and health and demographic risk. For product safety and quality, we include discussion of product recalls, losing customer trust through product quality concerns. For privacy and data security, we have discussions of data security breaches, the controversial use of personal data. For chemical safety, we include discussions of the use or presence of chemicals of concern. For consumer financial protection, we include discussions of the transparency of financial products. For health and demographic risk, we include discussions of public health trends.\n\nCommunity Relations: This topic includes discussions of a firm\'s interaction with its local communities, including access to communications, access to finance, and access to healthcare. We include discussions about opportunities in historically underserved markets, such as developing countries and underserved populations, and relevant philanthropic efforts.\n\nCorporate Governance: This topic includes discussions on shareholders and ownership, board of directors, executive pay, and internal controls. For shareholders and ownership, we include discussions regarding ownership structure, control structure, and shareholders. For the board of directors, we include discussions of the board\'s independence from management, board skills and diversity, and board effectiveness. For executive pay, we include CEO and other executives\' pay practices. For internal control, we consider internal controls, audit matters, and internal audit matters.\n\nBusiness Ethics & Values: This topic includes discussions about ethical components such as a firm\'s values and controversies. We include discussions about the ethical conduct of business, fraud, corruption, bribery, fiduciary responsibilities, conflicts of interest, misrepresentation, bias, negligence, political contributions, negative accounting events, and other behaviors which may have ethical components.\n\nNon-ESG: The paragraph does not primarily discuss any of the above ESG topics. Typical Non-ESG content includes: general financial performance, revenue/earnings discussions, market competition, product/service descriptions, operational logistics, legal boilerplate, accounting policies, and general business strategy unrelated to ESG.\n\n=== IMPORTANT RULES ===\n- Choose the SINGLE most relevant category.\n- Only classify as an ESG category if the paragraph PRIMARILY discusses that topic.\n- If uncertain between an ESG category and Non-ESG, lean toward Non-ESG.\n\n=== PARAGRAPH TO CLASSIFY ===\nBUSINESS AND OPERATIONAL RISK FACTORS\nThe single largest variable that affects the company’s results of operations is the price of crude oil, which can be influenced by general economic conditions, industry production and inventory levels, technology advancements, production quotas or other actions that might be imposed by the Organization of Petroleum Exporting Countries or other producers, weather-related damage and disruptions due to other natural or human causes beyond our control (including without limitation due to the COVID-19 pandemic), competing fuel prices, geopolitical risks, the pace of energy transition, and governmental regulations and policies regarding the development of oil and gas reserves. Chevron evaluates the risk of changing commodity prices as a core part of its business planning process. An investment in the company carries significant exposure to fluctuations in global crude oil prices. Extended periods of low prices for crude oil can have a material adverse impact on the company’s results of operations, financial condition and liquidity. Among other things, the company’s upstream earnings, cash flows, and capital and exploratory expenditure programs could be negatively affected, as could its production and proved reserves. Upstream assets may also become impaired. Downstream earnings could be negatively affected because they depend upon the supply and demand for refined products and the associated margins on refined product sales. A significant or sustained decline in liquidity could adversely affect the company’s credit ratings, potentially increase financing costs and reduce access to capital markets. The company may be unable to realize anticipated cost savings, expenditure reductions and asset sales that are intended to compensate for such downturns, and such downturns may also slow the pace and scale at which we are able to invest in new business lines such as the lower carbon businesses associated with our Chevron New Energies organization.<end_of_turn>\n<start_of_turn>model\n<reasoning>\nKey keywords and concepts in the paragraph include crude oil prices, commodity price fluctuations, production, reserves, upstream/downstream earnings, cash flows, capital and exploratory expenditures, asset impairment, liquidity, credit ratings, and investment in lower carbon businesses as a business impact. These concepts map to Non-ESG because the paragraph discusses financial and operational risks tied to market prices, production and investment impacts rather than policies or practices addressing ESG topics (it frames energy transition and regulations as market drivers affecting financial performance rather than as environmental strategy or emissions commitments). While it mentions "pace of energy transition" and "lower carbon businesses," those references are contextual drivers of financial risk, not substantive climate initiatives or sustainability programs, so Climate Change and other environmental categories do not apply.\n</reasoning>\n<label>Non-ESG</label><end_of_turn>\n'

Now let's print the masked out example - you should see only the answer is present:

In [13]:
tokenizer.decode([tokenizer.pad_token_id if x == -100 else x for x in trainer.train_dataset[100]["labels"]]).replace(tokenizer.pad_token, " ")

'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <reasoning>\nKey keywords and concepts in the paragraph include crude oil prices, commodity price fluctuations, production, reserves, upstream/downstream earnings, cash flows, capital and exploratory expenditures, asset impairment, liquidity, credit ratings, and investment in lower carbon businesses as a business impact. These concepts map to Non-ESG because the paragraph discusses financial and operational risks tied to market prices, production and investment impacts rather than policies or practices addressing ESG topics (it frames energy transition and regulations as market drivers affecting financial performance rather than as environmental strategy or emissions commitments). While it mentions "pace of energy transition" and "lower carbon businesses," those references are contextual drivers of financial risk, not substantive climate initiatives or sustainability programs, so Climate Change and other environmental categories do not apply.\n</reasoning>\n<label>Non-ESG</label><end_of_turn>\n'

In [14]:
# @title Show current memory stats
gpu_stats = torch.cuda.get_device_properties(0)
start_gpu_memory = round(torch.cuda.max_memory_reserved() / 1024 / 1024 / 1024, 3)
max_memory = round(gpu_stats.total_memory / 1024 / 1024 / 1024, 3)
print(f"GPU = {gpu_stats.name}. Max memory = {max_memory} GB.")
print(f"{start_gpu_memory} GB of memory reserved.")

GPU = NVIDIA GeForce RTX 4090. Max memory = 23.518 GB.
4.416 GB of memory reserved.

Let's train the model! To resume a training run, set `trainer.train(resume_from_checkpoint = True)`

In [15]:
trainer_stats = trainer.train()

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 779 | Num Epochs = 1 | Total steps = 98
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 29,802,496 of 4,329,881,968 (0.69% trained)

In [16]:
# @title Show final memory and time stats
used_memory = round(torch.cuda.max_memory_reserved() / 1024 / 1024 / 1024, 3)
used_memory_for_lora = round(used_memory - start_gpu_memory, 3)
used_percentage = round(used_memory / max_memory * 100, 3)
lora_percentage = round(used_memory_for_lora / max_memory * 100, 3)
print(f"{trainer_stats.metrics['train_runtime']} seconds used for training.")
print(
  f"{round(trainer_stats.metrics['train_runtime']/60, 2)} minutes used for training."
)
print(f"Peak reserved memory = {used_memory} GB.")
print(f"Peak reserved memory for training = {used_memory_for_lora} GB.")
print(f"Peak reserved memory % of max memory = {used_percentage} %.")
print(f"Peak reserved memory for training % of max memory = {lora_percentage} %.")

605.728 seconds used for training.
10.1 minutes used for training.
Peak reserved memory = 16.727 GB.
Peak reserved memory for training = 12.311 GB.
Peak reserved memory % of max memory = 71.124 %.
Peak reserved memory for training % of max memory = 52.347 %.

<a name="Inference"></a>
### Inference
Let's run the model via Unsloth native inference! According to the `Gemma-3` team, the recommended settings for inference are `temperature = 1.0, top_p = 0.95, top_k = 64`

In [17]:
SYSTEM_PROMPT = """You are an ESG (Environmental, Social, and Governance) risk classification expert specialized in analyzing U.S. 10-K filings. Your task is to classify paragraphs from Item 1A (Risk Factors) sections into exactly one of the following 9 categories.

You must respond with ONLY the category name. Do not include any explanation, reasoning, numbering, or additional text.

Valid category names (respond with one of these exactly):
- Climate Change
- Natural Capital
- Pollution & Waste
- Human Capital
- Product Liability
- Community Relations
- Corporate Governance
- Business Ethics & Values
- Non-ESG

CRITICAL: Your entire response must be EXACTLY one of the 9 category names above. No other words, punctuation, or characters. Maximum 4 words."""

USER_PROMPT_TEMPLATE = """Classify the following paragraph from a 10-K filing into one of the 9 ESG categories based on the definitions and examples below.

=== CATEGORY DEFINITIONS ===

Appendix: Detail description and examples of the eight ESG topics:
Climate Change: This topic includes discussions about carbon emissions or climate change, including
initiatives to increase carbon efficiency, environmental technologies, renewable energy, and the
development or refurbishment of buildings with leading ecological design features. The following are
some examples:
- We are also excited about our commitment to securing 100% of our purchased electricity from
renewable sources by 2025, reducing our operational carbon footprint by 30%.
- In 2018, we acquired a 43.83% interest in Silicon Ranch, a leading US developer, owner, and
operator of solar assets. In 2019, Silicon Ranch announced the launch of a program that
combines clean electricity generation with carbon sequestration and ecosystem restoration.
- Beginning in 2012 through the end of 2016, we have converted 19 plants from coal to natural
gas or steam.
- 40% of our operations are to be certified under a green building standard by 2018.
Natural Capital: This topic includes discussions about water stress, biodiversity, land use, and raw
materials sourcing. For water stress, we include discussions of how companies manage risks of water
shortages, such as by employing efficient water processes, water recycling, and alternative water
sources. For biodiversity and land use, we include discussions about programs and policies designed to
protect biodiversity and address community land-use concerns. For raw materials sourcing, we include
discussions about policies and procedures to source materials with lower environmental impact, such
as seafood/aquaculture, timber/paper, palm oil, beef/dairy, leather, and cotton. The following are some
examples:
- This year, we continued Stella Artois' Buy a Lady a Drink program with Water.org, which aims
to tackle the global water crisis. Having to date supported nearly 800,000 people, we recently
announced our ambition to provide access to safe water to 3.5 million people in the developing
world by 2020.
- At the chemical complex in the Netherlands, our biodiversity action plan has helped maintain a
variety of flora and fauna. It has also raised awareness about biodiversity among technical
staff. For example, in 2019, planned maintenance work was adjusted after operators found a
protected bird species nesting in equipment.
- 100% of the paper used in our U.S direct marketing efforts was certified to be from sustainably
managed forests.
- During the period, Kimco remediated soil as a part of major development or redevelopment
projects at the following locations: Dania Pointe (Dania Beach, FL), Suburban Square
(Ardmore, PA), Lincoln Square (Philadelphia, PA).
Pollution and Waste: This topic includes discussions about toxic emissions, packaging materials, and
electronic waste. For toxic emissions and waste, we include discussions of pollution, contamination,
and emission of toxic and carcinogenic substances and wastewater. For packaging materials and waste,
we include discussions of product packaging content and end-of-life recycling or disposal of
packaging materials. We include discussions about the recycling and removal of end-of-life electronic
products for electronic waste. The following are some examples:
- We also have programs in place to reduce the number of operational spills over the long term.
In 2019, we continued to carry out vital work to clean up Bodo, an area badly affected by oil
spills.
- Through lightweighting and packaging reduction initiatives, we have reduced the amount of
packaging we use by 126,800 tons since 2012, exceeding our 2017 reduction goal of 100,000
tons a year early.
- All of these programs reduce waste and encourage reuse by ensuring that valuable products
can go back into the hands of customers rather than being sent to landfills.
- Several years ago, we saw an opportunity to create a single streamlined solution for tenants
that could provide them with more reliable and cost-effective waste services.
Human Capital: This topic includes discussions about labor management, health and safety, human
capital development and training, and supply chain labor standards. For labor management, we include
discussions workforce management, risk of workflow disruptions, labor productivity issues, employee
diversity, and pay equality (non-executive). For health and safety, we include discussions of employee
health and safety (H&S) programs such as H&S policies and their implementations, H&S training, and
safety certifications. For human capital development and training, we include discussions of the ability
to attract, retain, and develop human capital based on benefits, training, development programs, and
employee engagement provided. For supply chain labor standards, we include discussions of supply
chain production disruptions and brand value damage due to sub-standard treatment of workers in the
company's supply chain or reliance on raw materials that originate in areas associated with severe
human rights and labor rights issues (e.g., slave labor and child labor). The following are some
examples:
- We provide formal channels to guide colleagues and leaders on decisions related to flextime,
part-time, compressed work weeks, job sharing, and remote work.
- We use technology systems on our trucks to track driver behaviors, which has increased
accountability among our managers and resulted in a reduction in speeding and safer fleet
operations.
- Enterprise Leadership delivers targeted leadership development programs to colleagues at
specific stages of their careers.
- This can lead to unfair treatment of workers, which is why we continue our efforts to source
secondary raw materials in a way that's aligned with our "Fair and Equal" agenda.
Product Liability: This topic includes discussing product safety and quality, privacy and data
security, chemical safety, consumer financial protection, and health and demographic risk. For product
safety and quality, we include discussion of product recalls, losing customer trust through product
quality concerns, or product safety and quality certifications. For privacy and data security, we have
discussions of data security breaches, the controversial use of personal data, and company data privacy
policies and data security management systems. For chemical safety, we include discussions of the use
or presence of chemicals of concern and procedures relating to chemical safety and its impact on
customers. For consumer financial protection, we include discussions of the transparency of financial
products based on borrowers' ability to repay and initiatives to protect customers through product
transparency. For health and demographic risk, we include discussions of public health trends and
demographic changes, growth opportunities in the market for healthier products, and improved
nutritional profiles. The following are some examples:
- Our products are designed and tested to comply with all applicable safety regulations in the
countries where the products are sold.
- Information Security oversees a comprehensive program to help predict, protect, detect,
respond to, and recover from cyberattacks.
- For example, we have phased out any chemicals suspected of causing medical reactions or
harm.
- The Smarter CreditTM Center includes resources to help customers understand, build, and
improve credit, as well as manage debt and plan for large purchases.
Community Relations: This topic includes discussions of a firm's interaction with its local
communities, including access to communications, access to finance, and access to healthcare. We
include discussions about opportunities in historically underserved markets, such as developing
countries and underserved populations, and relevant philanthropic efforts. The following are some
examples:
- We've gone from sourcing 70% of barley locally in 2014 to 86% in 2016, and we're on track to
achieve 100% local sourcing by 2017.
- In addition, we have committed to a package of public interest commitments, which include a
commitment to invest 1 billion ZAR in areas including supporting smallholder farmers and
enterprise development.
- We aim to improve access for local people to health care and treatments for diseases such as
cancer.
- Participants volunteer for significant causes such as disaster relief, hunger, medical research,
home building or youth mentoring, and groups are encouraged to serve together as a means of
multiplying their impact and fostering team spirit.
Corporate Governance: This topic includes discussions on shareholders and ownership, board of
directors, executive pay, and internal controls. For shareholders and ownership, we include discussions
regarding ownership structure, control structure, and shareholders. For the board of directors, we
include discussions of the board's independence from management, board skills and diversity, and
board effectiveness. For executive pay, we include CEO and other executives' pay practices and 
specific pay figures, performance incentives, and overall pay plan design. For internal control, we
consider internal controls, audit matters, audit committee matters, and internal audit matters. The
following are some examples:
- Based on filings made under Sections 13(d) and 13(g) of the Securities Exchange Act of 1934,
as amended, as of December 31, 2020, the only persons or entities known by us to be a
beneficial owner of more than 5% of our common stock were as follows.
- Our Board is composed entirely of independent directors other than our chairman and CEO,
and is diverse, with diversity reflecting gender, age, race, ethnicity, background, professional
experience, and perspectives.
- We announced plans in 2018 to link executive remuneration to short-term targets to reduce the
Net Carbon Footprint of the energy products we sell, including our customers' emissions from
their use of our energy products.
- The appointment by the Audit and Compliance Committee of the Company's Board of
Directors of PricewaterhouseCoopers LLP, as an independent registered public accounting
firm for the Company, to audit the financial statements of the Company and its subsidiaries for
2022 is hereby ratified and approved.
Business Ethics and Values: This topic includes discussions about ethical components such as a
firm's values and controversies. We include discussions about the ethical conduct of business, fraud,
corruption, bribery, fiduciary responsibilities, conflicts of interest, misrepresentation, bias, negligence,
political contributions, negative accounting events, and other behaviors which may have ethical
components. The following is an example:
- At the heart of our culture is what we call our Blue Box Values - a set of seven guiding
principles that every employee pledges to embrace and work by each day.
- Huntington is dedicated to uncompromising integrity in all that it does and how it relates to its
internal colleagues and to persons outside Huntington.
- In reaching this settlement, we neither admitted nor denied the claims in the order and agreed
to pay a civil monetary penalty of $5.5 million.
- In addition, certain private parties as well as state attorneys general and other antitrust
authorities may challenge the transactions under U.S. or foreign antitrust laws under certain
circumstances.

Non-ESG
The paragraph does not primarily discuss any of the above ESG topics. Typical Non-ESG content includes: general financial performance, revenue/earnings discussions, market competition, product/service descriptions, operational logistics, legal boilerplate, accounting policies, and general business strategy unrelated to ESG.

=== IMPORTANT RULES ===
- Choose the SINGLE most relevant category. If a paragraph touches multiple ESG topics, select the PRIMARY one.
- Only classify as an ESG category if the paragraph PRIMARILY discusses that topic. Incidental mentions do not qualify.
- If uncertain between an ESG category and Non-ESG, lean toward Non-ESG.
- Respond with ONLY the category name, nothing else.

=== PARAGRAPH TO CLASSIFY ===
{text}

Remember: Output ONLY the category name. One of the 9 valid labels. No explanation. No punctuation. Maximum 4 words."""

In [18]:
# from unsloth.chat_templates import get_chat_template
# tokenizer = get_chat_template(
#   tokenizer,
#   chat_template = "gemma-3",
# )

# text = "Our results can fluctuate due to the effects of weather, natural disasters and seasonality.\n\nOur results of operations are impacted by severe weather, natural disasters and seasonality. Severe weather conditions and natural disasters (or other environmental events) can significantly disrupt service and create air traffic control problems. These events decrease revenue and can also increase costs. In addition, increases in the frequency, severity or duration of thunderstorms, hurricanes, typhoons or other severe weather events, including from changes in the global climate, could result in increases in delays and cancellations, turbulence-related injuries and fuel consumption to avoid such weather, any of which could result in loss of revenue and higher costs. In addition, demand for air travel is typically higher in the June and September quarters, particularly in our international markets, because there is more vacation travel during these periods than during the remainder of the year. The seasonal shifting of demand causes our financial results to vary on a seasonal basis. Because of fluctuations in our results from weather, natural disasters and seasonality, operating results for a historical period are not necessarily indicative of operating results for a future period and operating results for an interim period are not necessarily indicative of operating results for an entire year."

# messages = [
#    {
#     "role": "system",
#     "content": [{
#      "type" : "text",
#      "text" : SYSTEM_PROMPT
#     }]
#    },
#    {
#     "role": "user",
#     "content": [{
#      "type" : "text",
#      "text" : USER_PROMPT_TEMPLATE.replace("{text}", text)
#     }]
#    },
#   ]
# inputs = tokenizer.apply_chat_template(
#   messages,
#   add_generation_prompt = True, # Must add for generation
#   tokenize = True,
#   return_tensors = "pt",
#   return_dict = True,
# )
# outputs = model.generate(
#   **inputs.to("cuda"),
#   max_new_tokens = 4096, # Increase for longer outputs!
#   # Recommended Gemma-3 settings!
#   temperature = 1, top_p = 0.95, top_k = 64,
# )
# tokenizer.batch_decode(outputs)

 You can also use a `TextStreamer` for continuous inference - so you can see the generation token by token, instead of waiting the whole time!

In [19]:
# # messages = [{
# #   "role": "user",
# #   "content": [{"type" : "text", "text" : "Why is the sky blue?",}]
# # }]


# messages = [
#    {
#     "role": "system",
#     "content": [{
#      "type" : "text",
#      "text" : ""
#     }]
#    },
#    {
#     "role": "user",
#     "content": [{
#      "type" : "text",
#      "text" : " "
#     }]
#    },
#   ]
# inputs = tokenizer.apply_chat_template(
#   messages,
#   add_generation_prompt = True, # Must add for generation
#   tokenize = True,
#   return_tensors = "pt",
#   return_dict = True,
# )

# from transformers import TextStreamer
# _ = model.generate(
#   **inputs.to("cuda"),
#   max_new_tokens = 512, # Increase for longer outputs!
#   # Recommended Gemma-3 settings!
#   temperature = 1.0, top_p = 0.95, top_k = 64,
#   streamer = TextStreamer(tokenizer, skip_prompt = True),
# )

<a name="Evaluation"></a>
### Model Evaluation
Let's evaluate the model on the validation dataset and calculate metrics including F1 score, accuracy, precision, and recall.

In [20]:
import json
import pandas as pd

TEST_PATH = "../../data/processed/step3_annotation/test_labeled.json"

with open(TEST_PATH, "r", encoding="utf-8") as f:
  test_data = json.load(f)

test_df = pd.DataFrame(test_data)

print("Test size:", len(test_df))
print(test_df[["paragraph_id", "combined_text", "label"]].head())

Test size: 200
        paragraph_id                                      combined_text  \
0  SPG_2022_RISK_015  Risks Relating to Retail Operations\nIf a depa...
1  TYL_2022_RISK_032  Risks Related to Our Indebtedness\nBank Nation...
2  FRT_2022_RISK_043  We face risks relating to cyber attacks that c...
3  DHI_2021_RISK_063  General Risk Factors\nWe may also be required ...
4  AMT_2022_RISK_051  Risks Related to the Operation of Our Business...

               label
0            Non-ESG
1            Non-ESG
2  Product Liability
3  Product Liability
4  Product Liability

In [21]:
import re
import pandas as pd
from IPython.display import display
from tqdm import tqdm
from sklearn.metrics import (
  accuracy_score,
  precision_recall_fscore_support,
  classification_report,
  confusion_matrix,
)

LABELS = [
  "Climate Change",
  "Natural Capital",
  "Pollution & Waste",
  "Human Capital",
  "Product Liability",
  "Community Relations",
  "Corporate Governance",
  "Business Ethics & Values",
  "Non-ESG",
]

LABELS_SORTED = sorted(LABELS, key=len, reverse=True)
INVALID_LABEL = "__INVALID__"

XML_SYSTEM_PROMPT = SYSTEM_PROMPT + "\n\nYou must respond in XML using exactly this format:\n<reasoning>your reasoning</reasoning>\n<label>one valid category</label>"
XML_USER_PROMPT_TEMPLATE = USER_PROMPT_TEMPLATE + "\n\nReturn your final answer in this exact XML format:\n<reasoning>brief reasoning</reasoning>\n<label>one valid category</label>"


def canonicalize_label(text):
  if text is None:
    return None

  text = re.sub(r"\s+", " ", str(text)).strip().strip("\"'")
  if not text:
    return None

  aliases = {
    "pollution and waste": "Pollution & Waste",
    "business ethics and values": "Business Ethics & Values",
    "non esg": "Non-ESG",
  }

  lower = text.lower()
  if lower in aliases:
    return aliases[lower]

  for label in LABELS_SORTED:
    if lower == label.lower():
      return label

  return None


def extract_label(text):
  if text is None:
    return None

  text = str(text).strip()
  if not text:
    return None

  match = re.search(r"<label>\s*(.*?)\s*</label>", text, re.IGNORECASE | re.DOTALL)
  if match:
    return canonicalize_label(match.group(1))

  for label in LABELS_SORTED:
    if text == label or text.startswith(label):
      return label

  patterns = [
    r"(?i)(?:answer|label|category)\s*:\s*(.+)$",
    r"(?i)(?:classified as|category is|label is)\s*:?\s*(.+)$",
    r"(?i)(?:the correct category is)\s*:?\s*(.+)$",
  ]
  for pattern in patterns:
    match = re.search(pattern, text)
    if match:
      candidate = canonicalize_label(match.group(1).strip())
      if candidate is not None:
        return candidate

  tail = text[-200:]
  matched = [label for label in LABELS_SORTED if re.search(rf"(?i)\b{re.escape(label)}\b", tail)]
  if len(matched) == 1:
    return matched[0]

  matched = [label for label in LABELS_SORTED if re.search(rf"(?i)\b{re.escape(label)}\b", text)]
  matched = list(dict.fromkeys(matched))
  if len(matched) == 1:
    return matched[0]

  return None


def build_messages(paragraph_text):
  return [
    {
      "role": "system",
      "content": [{"type": "text", "text": XML_SYSTEM_PROMPT}],
    },
    {
      "role": "user",
      "content": [{"type": "text", "text": XML_USER_PROMPT_TEMPLATE.replace("{text}", paragraph_text)}],
    },
  ]


y_true_parseable = []
y_pred_parseable = []
y_true_all = []
y_pred_all = []
failed_cases = []

print(f"Evaluating on {len(test_df)} test samples...\n")

for _, row in tqdm(test_df.iterrows(), total=len(test_df), desc="Evaluating"):
  paragraph_id = row.get("paragraph_id")
  paragraph_text = row["combined_text"]
  gt_label = canonicalize_label(row["label"])

  if gt_label is None:
    failed_cases.append({
      "paragraph_id": paragraph_id,
      "reason": "invalid_ground_truth",
      "ground_truth": row.get("label"),
    })
    continue

  y_true_all.append(gt_label)

  try:
    messages = build_messages(paragraph_text)

    inputs = tokenizer.apply_chat_template(
      messages,
      add_generation_prompt=True,
      tokenize=True,
      return_tensors="pt",
      return_dict=True,
    )
    inputs = {k: v.to("cuda") for k, v in inputs.items()}

    outputs = model.generate(
      **inputs,
      max_new_tokens=512,
      do_sample=False,
      temperature=None,
      top_p=None,
      use_cache=True,
      pad_token_id=tokenizer.eos_token_id,
    )

    input_len = inputs["input_ids"].shape[1]
    generated_tokens = outputs[0][input_len:]
    decoded = tokenizer.decode(generated_tokens, skip_special_tokens=True).strip()
    pred_label = extract_label(decoded)

    if len(y_pred_all) < 5:
      print("RAW OUTPUT:", repr(decoded))
      print("PARSED PRED:", pred_label)
      print("GT:", gt_label)
      print("-" * 80)

    if pred_label is None:
      y_pred_all.append(INVALID_LABEL)
      failed_cases.append({
        "paragraph_id": paragraph_id,
        "reason": "prediction_parse_failed",
        "ground_truth": gt_label,
        "raw_output": decoded,
      })
      continue

    y_true_parseable.append(gt_label)
    y_pred_parseable.append(pred_label)
    y_pred_all.append(pred_label)

  except Exception as exc:
    y_pred_all.append(INVALID_LABEL)
    failed_cases.append({
      "paragraph_id": paragraph_id,
      "reason": "exception",
      "ground_truth": gt_label,
      "error": str(exc),
    })

total_eval = len(y_true_all)
num_parseable = len(y_true_parseable)
num_failed = len(failed_cases)
parse_fail_rate = num_failed / total_eval if total_eval else 0.0

print("\n=== Evaluation Summary ===")
print(f"Total evaluated samples: {total_eval}")
print(f"Parseable predictions:  {num_parseable}")
print(f"Failed predictions:   {num_failed}")
print(f"Parse failure rate:   {parse_fail_rate:.4f}")

print("\n" + "=" * 70)
print("PARSEABLE-ONLY METRICS")
print("=" * 70)

if y_true_parseable and set(y_true_parseable) & set(LABELS):
  acc_p = accuracy_score(y_true_parseable, y_pred_parseable)
  macro_p_p, macro_r_p, macro_f1_p, _ = precision_recall_fscore_support(
    y_true_parseable,
    y_pred_parseable,
    labels=LABELS,
    average="macro",
    zero_division=0,
  )
  weighted_p_p, weighted_r_p, weighted_f1_p, _ = precision_recall_fscore_support(
    y_true_parseable,
    y_pred_parseable,
    labels=LABELS,
    average="weighted",
    zero_division=0,
  )

  print(f"Accuracy:      {acc_p:.4f}")
  print(f"Macro Precision:   {macro_p_p:.4f}")
  print(f"Macro Recall:    {macro_r_p:.4f}")
  print(f"Macro F1:      {macro_f1_p:.4f}")
  print(f"Weighted Precision: {weighted_p_p:.4f}")
  print(f"Weighted Recall:   {weighted_r_p:.4f}")
  print(f"Weighted F1:     {weighted_f1_p:.4f}")

  print("\n=== Classification Report (Parseable-only) ===")
  print(classification_report(y_true_parseable, y_pred_parseable, labels=LABELS, zero_division=0))

  cm_parseable = confusion_matrix(y_true_parseable, y_pred_parseable, labels=LABELS)
  display(pd.DataFrame(cm_parseable, index=LABELS, columns=LABELS))
else:
  print("No parseable predictions available.")

print("\n" + "=" * 70)
print("END-TO-END METRICS (failed outputs counted as wrong)")
print("=" * 70)

if y_true_all and set(y_true_all) & set(LABELS):
  acc_all = accuracy_score(y_true_all, y_pred_all)
  macro_p_all, macro_r_all, macro_f1_all, _ = precision_recall_fscore_support(
    y_true_all,
    y_pred_all,
    labels=LABELS,
    average="macro",
    zero_division=0,
  )
  weighted_p_all, weighted_r_all, weighted_f1_all, _ = precision_recall_fscore_support(
    y_true_all,
    y_pred_all,
    labels=LABELS,
    average="weighted",
    zero_division=0,
  )

  print(f"Accuracy:      {acc_all:.4f}")
  print(f"Macro Precision:   {macro_p_all:.4f}")
  print(f"Macro Recall:    {macro_r_all:.4f}")
  print(f"Macro F1:      {macro_f1_all:.4f}")
  print(f"Weighted Precision: {weighted_p_all:.4f}")
  print(f"Weighted Recall:   {weighted_r_all:.4f}")
  print(f"Weighted F1:     {weighted_f1_all:.4f}")

  print("\n=== Classification Report (End-to-end) ===")
  print(classification_report(y_true_all, y_pred_all, labels=LABELS, zero_division=0))

  cm_all_labels = LABELS + [INVALID_LABEL]
  cm_all = confusion_matrix(y_true_all, y_pred_all, labels=cm_all_labels)
  print("\n=== Confusion Matrix (End-to-end) ===")
  print("Rows = ground truth, Columns = prediction")
  display(pd.DataFrame(cm_all, index=cm_all_labels, columns=cm_all_labels))

  invalid_pred_count = sum(pred == INVALID_LABEL for pred in y_pred_all)
  print(f"\nInvalid prediction count: {invalid_pred_count}")
else:
  print("No end-to-end samples available.")

if failed_cases:
  failed_df = pd.DataFrame(failed_cases)
  print("\n=== Failed Cases by Reason ===")
  display(failed_df["reason"].value_counts().rename_axis("reason").reset_index(name="count"))
  print("\n=== Failed Cases (head 20) ===")
  display(failed_df.head(20))

Evaluating on 200 test samples...

Evaluating:   0%|          | 1/200 [00:15<52:28, 15.82s/it]

RAW OUTPUT: '<reasoning>The paragraph discusses retail operations, tenant closures, lease re-tenanting, and potential rent defaults, which are business and operational risks rather than environmental, social, or governance issues as defined; it does not address climate, natural capital, pollution, human capital, product liability, community relations, corporate governance, or ethics.\n</reasoning>\n<label>Non-ESG</label>'
PARSED PRED: Non-ESG
GT: Non-ESG
--------------------------------------------------------------------------------

Evaluating:   1%|          | 2/200 [00:25<39:53, 12.09s/it]

RAW OUTPUT: '<reasoning>The paragraph discusses debt repayment, repurchase obligations, and refinancing risks tied to financial performance and legal/regulatory constraints, which map to general financial and legal risk rather than any ESG topic defined here. It does not address environmental, social, governance, or ethical issues, so none of the ESG categories apply.\n</reasoning>\n<label>Non-ESG</label>'
PARSED PRED: Non-ESG
GT: Non-ESG
--------------------------------------------------------------------------------

Evaluating:   2%|▏         | 3/200 [00:35<36:50, 11.22s/it]

RAW OUTPUT: '<reasoning>The paragraph discusses cyber attacks, data security breaches, and measures to prevent and mitigate them, which map to the Product Liability definition of privacy and data security risks and company data privacy policies. It is not primarily about climate, natural resources, pollution, human capital, governance, ethics, or community relations, so those ESG categories do not apply.\n</reasoning>\n<label>Product Liability</label>'
PARSED PRED: Product Liability
GT: Product Liability
--------------------------------------------------------------------------------

Evaluating:   2%|▏         | 4/200 [00:47<38:12, 11.70s/it]

RAW OUTPUT: '<reasoning>The paragraph discusses information technology failures, security breaches, privacy and data protection laws, regulatory compliance, and cybersecurity measures, which map to product safety and quality and privacy and data security aspects of the Product Liability definition. It covers data security breaches, regulatory compliance obligations, and potential litigation and reputational damage from noncompliance, so it is not primarily about climate, natural capital, pollution, human capital, community relations, corporate governance, or business ethics.\n</reasoning>\n<label>Product Liability</label>'
PARSED PRED: Product Liability
GT: Product Liability
--------------------------------------------------------------------------------

Evaluating:   2%|▎         | 5/200 [00:58<36:53, 11.35s/it]

RAW OUTPUT: '<reasoning>The paragraph discusses cybersecurity risks, data breaches, regulatory penalties, loss of customer trust, and insurance coverage for data privacy incidents, which map to the Product Liability definition of privacy and data security risks and potential harm to customers and reputation. It does not primarily address climate, natural resources, pollution, labor, governance, community relations, or business ethics topics.\n</reasoning>\n<label>Product Liability</label>'
PARSED PRED: Product Liability
GT: Product Liability
--------------------------------------------------------------------------------

Evaluating: 100%|██████████| 200/200 [35:56<00:00, 10.78s/it]

=== Evaluation Summary ===
Total evaluated samples: 200
Parseable predictions:  200
Failed predictions:   0
Parse failure rate:   0.0000

======================================================================
PARSEABLE-ONLY METRICS
======================================================================
Accuracy:      0.8250
Macro Precision:   0.6717
Macro Recall:    0.4637
Macro F1:      0.5312
Weighted Precision: 0.8372
Weighted Recall:   0.8250
Weighted F1:     0.8114

=== Classification Report (Parseable-only) ===
                          precision    recall  f1-score   support

          Climate Change       1.00      0.50      0.67         6
         Natural Capital       0.00      0.00      0.00         0
       Pollution & Waste       0.80      0.67      0.73         6
           Human Capital       0.88      0.50      0.64        14
       Product Liability       0.96      0.85      0.90        27
     Community Relations       0.00      0.00      0.00         0
    Corporate Governance       0.60      0.25      0.35        12
Business Ethics & Values       1.00      0.44      0.62         9
                 Non-ESG       0.81      0.96      0.88       126

                accuracy                           0.82       200
               macro avg       0.67      0.46      0.53       200
            weighted avg       0.84      0.82      0.81       200

,Climate Change,Natural Capital,Pollution & Waste,Human Capital,Product Liability,Community Relations,Corporate Governance,Business Ethics & Values,Non-ESG
Climate Change,3,0,0,0,0,0,0,0,3
Natural Capital,0,0,0,0,0,0,0,0,0
Pollution & Waste,0,0,4,0,0,0,0,0,2
Human Capital,0,0,0,7,0,0,0,0,7
Product Liability,0,0,0,0,23,0,0,0,4
Community Relations,0,0,0,0,0,0,0,0,0
Corporate Governance,0,0,0,0,0,0,3,0,9
Business Ethics & Values,0,0,0,0,0,0,2,4,3
Non-ESG,0,2,1,1,1,0,0,0,121

======================================================================
END-TO-END METRICS (failed outputs counted as wrong)
======================================================================
Accuracy:      0.8250
Macro Precision:   0.6717
Macro Recall:    0.4637
Macro F1:      0.5312
Weighted Precision: 0.8372
Weighted Recall:   0.8250
Weighted F1:     0.8114

=== Classification Report (End-to-end) ===
                          precision    recall  f1-score   support

          Climate Change       1.00      0.50      0.67         6
         Natural Capital       0.00      0.00      0.00         0
       Pollution & Waste       0.80      0.67      0.73         6
           Human Capital       0.88      0.50      0.64        14
       Product Liability       0.96      0.85      0.90        27
     Community Relations       0.00      0.00      0.00         0
    Corporate Governance       0.60      0.25      0.35        12
Business Ethics & Values       1.00      0.44      0.62         9
                 Non-ESG       0.81      0.96      0.88       126

                accuracy                           0.82       200
               macro avg       0.67      0.46      0.53       200
            weighted avg       0.84      0.82      0.81       200


=== Confusion Matrix (End-to-end) ===
Rows = ground truth, Columns = prediction

,Climate Change,Natural Capital,Pollution & Waste,Human Capital,Product Liability,Community Relations,Corporate Governance,Business Ethics & Values,Non-ESG,__INVALID__
Climate Change,3,0,0,0,0,0,0,0,3,0
Natural Capital,0,0,0,0,0,0,0,0,0,0
Pollution & Waste,0,0,4,0,0,0,0,0,2,0
Human Capital,0,0,0,7,0,0,0,0,7,0
Product Liability,0,0,0,0,23,0,0,0,4,0
Community Relations,0,0,0,0,0,0,0,0,0,0
Corporate Governance,0,0,0,0,0,0,3,0,9,0
Business Ethics & Values,0,0,0,0,0,0,2,4,3,0
Non-ESG,0,2,1,1,1,0,0,0,121,0
__INVALID__,0,0,0,0,0,0,0,0,0,0

Invalid prediction count: 0

<a name="Save"></a>
### Saving, loading finetuned models
To save the final model as LoRA adapters, either use Hugging Face's `push_to_hub` for an online save or `save_pretrained` for a local save.

**[NOTE]** This ONLY saves the LoRA adapters, and not the full model. To save to 16bit or GGUF, scroll down!

In [23]:
model.save_pretrained("gemma_3_lora") # Local saving
tokenizer.save_pretrained("gemma_3_lora")
# model.push_to_hub("HF_ACCOUNT/gemma_3_lora", token = "YOUR_HF_TOKEN") # Online saving
# tokenizer.push_to_hub("HF_ACCOUNT/gemma_3_lora", token = "YOUR_HF_TOKEN") # Online saving

['gemma_3_lora/processor_config.json']

Now if you want to load the LoRA adapters we just saved for inference, set `False` to `True`:

In [26]:
if True:
  from unsloth import FastModel
  model, tokenizer = FastModel.from_pretrained(
    model_name = "gemma_3_lora", # YOUR MODEL YOU USED FOR TRAINING
    max_seq_length = 2048,
    load_in_4bit = True,
  )

messages = [{
  "role": "user",
  "content": [{"type" : "text", "text" : "What is Gemma-3?",}]
}]
inputs = tokenizer.apply_chat_template(
  messages,
  add_generation_prompt = True, # Must add for generation
  tokenize = True,
  return_tensors = "pt",
  return_dict = True,
)

from transformers import TextStreamer
_ = model.generate(
  **inputs.to("cuda"),
  max_new_tokens = 64, # Increase for longer outputs!
  # Recommended Gemma-3 settings!
  temperature = 1.0, top_p = 0.95, top_k = 64,
  streamer = TextStreamer(tokenizer, skip_prompt = True),
)

==((====))== Unsloth 2026.3.4: Fast Gemma3 patching. Transformers: 4.56.2.
  \\  /|  NVIDIA GeForce RTX 4090. Num GPUs = 1. Max memory: 23.518 GB. Platform: Linux.
O^O/ \_/ \  Torch: 2.9.1+cu128. CUDA: 8.9. CUDA Toolkit: 12.8. Triton: 3.5.1
\    /  Bfloat16 = TRUE. FA [Xformers = 0.0.33.post2. FA2 = False]
 "-____-"   Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
Gemma-3 is a family of open-and-free, lightweight, state-of-the-art language models released by Google DeepMind. Here's a breakdown of the key details:

**Key Features and Highlights:**

* **Family of Models:** There are different sizes within the Gemma family:

### Saving to float16 for VLLM

We also support saving to `float16` directly for deployment! We save it in the folder `gemma-3-finetune`. Set `if False` to `if True` to let it run!

In [ ]:
if False: # Change to True to save finetune!
  model.save_pretrained_merged("gemma-3-finetune", tokenizer)

If you want to upload / push to your Hugging Face account, set `if False` to `if True` and add your Hugging Face token and upload location!

In [ ]:
if False: # Change to True to upload finetune
  model.push_to_hub_merged(
    "HF_ACCOUNT/gemma-3-finetune", tokenizer,
    token = "YOUR_HF_TOKEN"
  )

### GGUF / llama.cpp Conversion
To save to `GGUF` / `llama.cpp`, we support it natively now for all models! For now, you can convert easily to `Q8_0, F16 or BF16` precision. `Q4_K_M` for 4bit will come later!

In [ ]:
if False: # Change to True to save to GGUF
  model.save_pretrained_gguf(
    "gemma_3_finetune",
    tokenizer,
    quantization_method = "Q8_0", # For now only Q8_0, BF16, F16 supported
  )

Likewise, if you want to instead push to GGUF to your Hugging Face account, set `if False` to `if True` and add your Hugging Face token and upload location!

In [ ]:
if False: # Change to True to upload GGUF
  model.push_to_hub_gguf(
    "HF_ACCOUNT/gemma_3_finetune",
    tokenizer,
    quantization_method = "Q8_0", # Only Q8_0, BF16, F16 supported
    token = "YOUR_HF_TOKEN",
  )

Now, use the `gemma-3-finetune.gguf` file or `gemma-3-finetune-Q4_K_M.gguf` file in llama.cpp.

And we're done! If you have any questions on Unsloth, we have a [Discord](https://discord.gg/unsloth) channel! If you find any bugs or want to keep updated with the latest LLM stuff, or need help, join projects etc, feel free to join our Discord!

Some other resources:
1. Train your own reasoning model - Llama GRPO notebook [Free Colab](https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/Llama3.1_(8B)-GRPO.ipynb)
2. Saving finetunes to Ollama. [Free notebook](https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/Llama3_(8B)-Ollama.ipynb)
3. Llama 3.2 Vision finetuning - Radiography use case. [Free Colab](https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/Llama3.2_(11B)-Vision.ipynb)
4. See notebooks for DPO, ORPO, Continued pretraining, conversational finetuning and more on our [documentation](https://unsloth.ai/docs/get-started/unsloth-notebooks)!

<div class="align-center">
 <a href="https://unsloth.ai"><img src="https://github.com/unslothai/unsloth/raw/main/images/unsloth%20new%20logo.png" width="115"></a>
 <a href="https://discord.gg/unsloth"><img src="https://github.com/unslothai/unsloth/raw/main/images/Discord.png" width="145"></a>
 <a href="https://unsloth.ai/docs/"><img src="https://github.com/unslothai/unsloth/blob/main/images/documentation%20green%20button.png?raw=true" width="125"></a>

 Join Discord if you need help + ⭐️ <i>Star us on <a href="https://github.com/unslothai/unsloth">Github</a> </i> ⭐️
</div>

 This notebook and all Unsloth notebooks are licensed [LGPL-3.0](https://github.com/unslothai/notebooks?tab=LGPL-3.0-1-ov-file#readme).