To run this, press "*Runtime*" and press "*Run all*" on a **free** Tesla T4 Google Colab instance!
<div class="align-center">
<a href="https://unsloth.ai/"><img src="https://github.com/unslothai/unsloth/raw/main/images/unsloth%20new%20logo.png" width="115"></a>
<a href="https://discord.gg/unsloth"><img src="https://github.com/unslothai/unsloth/raw/main/images/Discord button.png" width="145"></a>
<a href="https://unsloth.ai/docs/"><img src="https://github.com/unslothai/unsloth/blob/main/images/documentation%20green%20button.png?raw=true" width="125"></a> Join Discord if you need help + ⭐ <i>Star us on <a href="https://github.com/unslothai/unsloth">Github</a> </i> ⭐
</div>

To install Unsloth on your local device, follow [our guide](https://unsloth.ai/docs/get-started/install). This notebook is licensed [LGPL-3.0](https://github.com/unslothai/notebooks?tab=LGPL-3.0-1-ov-file#readme).

You will learn how to do [data prep](#Data), how to [train](#Train), how to [run the model](#Inference), & how to save it

### News

Train MoEs - DeepSeek, GLM, Qwen and gpt-oss 12x faster with 35% less VRAM. [Blog](https://unsloth.ai/docs/new/faster-moe)

You can now train embedding models 1.8-3.3x faster with 20% less VRAM. [Blog](https://unsloth.ai/docs/new/embedding-finetuning)

Ultra Long-Context Reinforcement Learning is here with 7x more context windows! [Blog](https://unsloth.ai/docs/new/grpo-long-context)

3x faster LLM training with 30% less VRAM and 500K context. [3x faster](https://unsloth.ai/docs/new/3x-faster-training-packing) • [500K Context](https://unsloth.ai/docs/new/500k-context-length-fine-tuning)

New in Reinforcement Learning: [FP8 RL](https://unsloth.ai/docs/new/fp8-reinforcement-learning) • [Vision RL](https://unsloth.ai/docs/new/vision-reinforcement-learning-vlm-rl) • [Standby](https://unsloth.ai/docs/basics/memory-efficient-rl) • [gpt-oss RL](https://unsloth.ai/docs/new/gpt-oss-reinforcement-learning)

Visit our docs for all our [model uploads](https://unsloth.ai/docs/get-started/unsloth-model-catalog) and [notebooks](https://unsloth.ai/docs/get-started/unsloth-notebooks).

### Installation

In [1]:
# %%capture
# import os, re
# if "COLAB_" not in "".join(os.environ.keys()):
#   !pip install unsloth # Do this in local & cloud setups
# else:
#   import torch; v = re.match(r'[\d]{1,}\.[\d]{1,}', str(torch.__version__)).group(0)
#   xformers = 'xformers==' + {'2.10':'0.0.34','2.9':'0.0.33.post1','2.8':'0.0.32.post2'}.get(v, "0.0.34")
#   !pip install sentencepiece protobuf "datasets==4.3.0" "huggingface_hub>=0.34.0" hf_transfer
#   !pip install --no-deps unsloth_zoo bitsandbytes accelerate {xformers} peft trl triton unsloth
# !pip install transformers==4.56.2
# !pip install --no-deps trl==0.22.2

### Unsloth

In [2]:
from unsloth import FastLanguageModel
import torch
max_seq_length = 4096 # Choose any! We auto support RoPE Scaling internally!
dtype = None # None for auto detection. Float16 for Tesla T4, V100, Bfloat16 for Ampere+
load_in_4bit = True # Use 4bit quantization to reduce memory usage. Can be False.

# 4bit pre quantized models we support for 4x faster downloading + no OOMs.
fourbit_models = [
  "unsloth/Llama-3.1-8B-bnb-4bit",   # Llama-3.1 2x faster
  "unsloth/Llama-3.1-8B-Instruct-bnb-4bit",
  "unsloth/Llama-3.1-70B-bnb-4bit",
  "unsloth/Llama-3.1-405B-bnb-4bit",  # 4bit for 405b!
  "unsloth/Mistral-Small-Instruct-2409",   # Mistral 22b 2x faster!
  "unsloth/mistral-7b-instruct-v0.3-bnb-4bit",
  "unsloth/Phi-3.5-mini-instruct",      # Phi-3.5 2x faster!
  "unsloth/Phi-3-medium-4k-instruct",
  "unsloth/gemma-2-9b-bnb-4bit",
  "unsloth/gemma-2-27b-bnb-4bit",      # Gemma 2x faster!

  "unsloth/Llama-3.2-1B-bnb-4bit",      # NEW! Llama 3.2 models
  "unsloth/Llama-3.2-1B-Instruct-bnb-4bit",
  "unsloth/Llama-3.2-3B-bnb-4bit",
  "unsloth/Llama-3.2-3B-Instruct-bnb-4bit",

  "unsloth/Llama-3.3-70B-Instruct-bnb-4bit" # NEW! Llama 3.3 70B!
] # More models at https://huggingface.co/unsloth

model, tokenizer = FastLanguageModel.from_pretrained(
  model_name = "unsloth/Llama-3.2-3B-Instruct", # or choose "unsloth/Llama-3.2-1B-Instruct"
  max_seq_length = max_seq_length,
  dtype = dtype,
  load_in_4bit = load_in_4bit,
  # token = "YOUR_HF_TOKEN", # HF Token for gated models
)

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.

/home/wa1ter/ESG-sft/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
 from .autonotebook import tqdm as notebook_tqdm

🦥 Unsloth Zoo will now patch everything to make training faster!
==((====))== Unsloth 2026.3.4: Fast Llama patching. Transformers: 5.2.0.
  \\  /|  NVIDIA GeForce RTX 4090. Num GPUs = 1. Max memory: 23.518 GB. Platform: Linux.
O^O/ \_/ \  Torch: 2.9.1+cu128. CUDA: 8.9. CUDA Toolkit: 12.8. Triton: 3.5.1
\    /  Bfloat16 = TRUE. FA [Xformers = 0.0.33.post2. FA2 = False]
 "-____-"   Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Loading weights: 100%|██████████| 254/254 [00:00<00:00, 716.42it/s, Materializing param=model.norm.weight]
Unsloth: Will load unsloth/llama-3.2-3b-instruct-unsloth-bnb-4bit as a legacy tokenizer.

We now add LoRA adapters so we only need to update 1 to 10% of all parameters!

In [3]:
model = FastLanguageModel.get_peft_model(
  model,
  r = 16, # Choose any number > 0 ! Suggested 8, 16, 32, 64, 128
  target_modules = ["q_proj", "k_proj", "v_proj", "o_proj",
           "gate_proj", "up_proj", "down_proj",],
  lora_alpha = 16,
  lora_dropout = 0, # Supports any, but = 0 is optimized
  bias = "none",  # Supports any, but = "none" is optimized
  # [NEW] "unsloth" uses 30% less VRAM, fits 2x larger batch sizes!
  use_gradient_checkpointing = "unsloth", # True or "unsloth" for very long context
  random_state = 3407,
  use_rslora = False, # We support rank stabilized LoRA
  loftq_config = None, # And LoftQ
)

Unsloth 2026.3.4 patched 28 layers with 28 QKV layers, 28 O layers and 28 MLP layers.

<a name="Data"></a>
### Data Prep
We now use the `Llama-3.1` format for conversation style finetunes. We use [Maxime Labonne's FineTome-100k](https://huggingface.co/datasets/mlabonne/FineTome-100k) dataset in ShareGPT style. But we convert it to HuggingFace's normal multiturn format `("role", "content")` instead of `("from", "value")`/ Llama-3 renders multi turn conversations like below:

```
<|begin_of_text|><|start_header_id|>user<|end_header_id|>

Hello!<|eot_id|><|start_header_id|>assistant<|end_header_id|>

Hey there! How are you?<|eot_id|><|start_header_id|>user<|end_header_id|>

I'm great thanks!<|eot_id|>
```

We use our `get_chat_template` function to get the correct chat template. We support `zephyr, chatml, mistral, llama, alpaca, vicuna, vicuna_old, phi3, llama3` and more.

In [4]:
from unsloth.chat_templates import get_chat_template

tokenizer = get_chat_template(
  tokenizer,
  chat_template = "llama-3.1",
)

def formatting_prompts_func(examples):
  convos = examples["conversations"]
  texts = [tokenizer.apply_chat_template(convo, tokenize = False, add_generation_prompt = False) for convo in convos]
  return { "text" : texts, }

from datasets import load_dataset
dataset = load_dataset("json", data_files="../../data/processed/step6_sft/train_sft_xml.json", split="train")
# dataset = load_dataset("mlabonne/FineTome-100k", split = "train")

We now use `standardize_sharegpt` to convert ShareGPT style datasets into HuggingFace's generic format. This changes the dataset from looking like:
```
{"from": "system", "value": "You are an assistant"}
{"from": "human", "value": "What is 2+2?"}
{"from": "gpt", "value": "It's 4."}
```
to
```
{"role": "system", "content": "You are an assistant"}
{"role": "user", "content": "What is 2+2?"}
{"role": "assistant", "content": "It's 4."}
```

In [5]:
from unsloth.chat_templates import standardize_sharegpt
dataset = standardize_sharegpt(dataset)
dataset = dataset.map(formatting_prompts_func, batched = True,)

We look at how the conversations are structured for item 5:

In [6]:
dataset[5]["conversations"]

[{'content': 'You are an ESG (Environmental, Social, and Governance) risk classification expert specialized in analyzing U.S. 10-K filings. Your task is to classify paragraphs from Item 1A (Risk Factors) sections into exactly one of the following 9 categories.\n\nValid category names:\n- Climate Change\n- Natural Capital\n- Pollution & Waste\n- Human Capital\n- Product Liability\n- Community Relations\n- Corporate Governance\n- Business Ethics & Values\n- Non-ESG',
 'role': 'system'},
 {'content': "Classify the following paragraph from a 10-K filing into one of the 9 ESG categories based on the definitions below.\n\n=== CATEGORY DEFINITIONS ===\nClimate Change: This topic includes discussions about carbon emissions or climate change, including initiatives to increase carbon efficiency, environmental technologies, renewable energy, and the development or refurbishment of buildings with leading ecological design features. The following are some examples:\n- We are also excited about our commitment to securing 100% of our purchased electricity from renewable sources by 2025, reducing our operational carbon footprint by 30%.\n- In 2018, we acquired a 43.83% interest in Silicon Ranch, a leading US developer, owner, and operator of solar assets.\n- Beginning in 2012 through the end of 2016, we have converted 19 plants from coal to natural gas or steam.\n- 40% of our operations are to be certified under a green building standard by 2018.\n\nNatural Capital: This topic includes discussions about water stress, biodiversity, land use, and raw materials sourcing. For water stress, we include discussions of how companies manage risks of water shortages, such as by employing efficient water processes, water recycling, and alternative water sources. For biodiversity and land use, we include discussions about programs and policies designed to protect biodiversity and address community land-use concerns. For raw materials sourcing, we include discussions about policies and procedures to source materials with lower environmental impact, such as seafood/aquaculture, timber/paper, palm oil, beef/dairy, leather, and cotton.\n\nPollution & Waste: This topic includes discussions about toxic emissions, packaging materials, and electronic waste. For toxic emissions and waste, we include discussions of pollution, contamination, and emission of toxic and carcinogenic substances and wastewater. For packaging materials and waste, we include discussions of product packaging content and end-of-life recycling or disposal of packaging materials. We include discussions about the recycling and removal of end-of-life electronic products for electronic waste.\n\nHuman Capital: This topic includes discussions about labor management, health and safety, human capital development and training, and supply chain labor standards. For labor management, we include discussions workforce management, risk of workflow disruptions, labor productivity issues, employee diversity, and pay equality (non-executive). For health and safety, we include discussions of employee health and safety (H&S) programs. For human capital development and training, we include discussions of the ability to attract, retain, and develop human capital based on benefits, training, development programs, and employee engagement provided. For supply chain labor standards, we include discussions of supply chain production disruptions and brand value damage due to sub-standard treatment of workers.\n\nProduct Liability: This topic includes discussing product safety and quality, privacy and data security, chemical safety, consumer financial protection, and health and demographic risk. For product safety and quality, we include discussion of product recalls, losing customer trust through product quality concerns. For privacy and data security, we have discussions of data security breaches, the controversial use of personal data. For chemical safety, we include discussions of the use or presence of chemicals of concern. For consumer financial protection, we include discussions of the transparency of financial products. For health and demographic risk, we include discussions of public health trends.\n\nCommunity Relations: This topic includes discussions of a firm's interaction with its local communities, including access to communications, access to finance, and access to healthcare. We include discussions about opportunities in historically underserved markets, such as developing countries and underserved populations, and relevant philanthropic efforts.\n\nCorporate Governance: This topic includes discussions on shareholders and ownership, board of directors, executive pay, and internal controls. For shareholders and ownership, we include discussions regarding ownership structure, control structure, and shareholders. For the board of directors, we include discussions of the board's independence from management, board skills and diversity, and board effectiveness. For executive pay, we include CEO and other executives' pay practices. For internal control, we consider internal controls, audit matters, and internal audit matters.\n\nBusiness Ethics & Values: This topic includes discussions about ethical components such as a firm's values and controversies. We include discussions about the ethical conduct of business, fraud, corruption, bribery, fiduciary responsibilities, conflicts of interest, misrepresentation, bias, negligence, political contributions, negative accounting events, and other behaviors which may have ethical components.\n\nNon-ESG: The paragraph does not primarily discuss any of the above ESG topics. Typical Non-ESG content includes: general financial performance, revenue/earnings discussions, market competition, product/service descriptions, operational logistics, legal boilerplate, accounting policies, and general business strategy unrelated to ESG.\n\n=== IMPORTANT RULES ===\n- Choose the SINGLE most relevant category.\n- Only classify as an ESG category if the paragraph PRIMARILY discusses that topic.\n- If uncertain between an ESG category and Non-ESG, lean toward Non-ESG.\n\n=== PARAGRAPH TO CLASSIFY ===\nRisks Related to Government Regulations\nThere has been, and likely will continue to be, increased regulation with respect to the collection, use and handling of an individual’s personal and financial information. Regulatory authorities around the world have passed or are considering legislative and regulatory proposals concerning data protection, privacy and data security. In the United States, Virginia and Colorado passed new comprehensive privacy legislation, and joined California (which further enhanced its existing privacy laws) in directly regulating the collection, use and sharing of personal information. These statutes create civil penalties for violations, and in the case of California, creates a private right of action for data breaches, that increases the risk of data breach litigation. Absent a pre-emptive Federal privacy law, as more states pass privacy legislation, there is a strong possibility that we will be forced to comply with a patchwork of inconsistent privacy regulations. Globally, personal information collected within the European Union and United Kingdom remains subject to the 2018 General Data Protection Regulation (GDPR), which is a UK and European Union-wide legal framework that governs data collection, use, and sharing of an individual’s personal data and creates a range of consumer privacy rights. GDPR provides significant penalties for non-compliance (up to 4% of global revenue) and EU data protection authorities have already issued significant fines. Similarly, in November 2021, China promulgated the Personal Information Protection Law (PIPL) which regulates the processing of personal information of individuals within China. If a company breaches PIPL it can be assessed fines of up 5% of its annual revenue. The interpretation and application of consumer and data protection laws and industry standards in the United States, Europe, China and elsewhere can be uncertain and currently is in flux.",
 'role': 'user'},
 {'content': '<reasoning>\nKey keywords and concepts in the paragraph include "collection, use and handling of an individual’s personal and financial information," "data protection, privacy and data security," "data breach litigation," "civil penalties," and references to GDPR, PIPL, and state privacy laws. These concepts map to the Product Liability definition because it explicitly includes privacy and data security risks and regulatory penalties for breaches of consumer data protection. Other ESG categories like Corporate Governance or Business Ethics could touch on compliance but do not focus on consumer data privacy and breach liabilities, and Climate Change, Natural Capital, Pollution & Waste, Human Capital, and Community Relations are not relevant to data protection.\n</reasoning>\n<label>Product Liability</label>',
 'role': 'assistant'}]

And we see how the chat template transformed these conversations.

**[Notice]** Llama 3.1 Instruct's default chat template default adds `"Cutting Knowledge Date: December 2023\nToday Date: 26 July 2024"`, so do not be alarmed!

In [7]:
dataset[5]["text"]

'<|begin_of_text|><|start_header_id|>system<|end_header_id|>\n\nCutting Knowledge Date: December 2023\nToday Date: 26 July 2024\n\nYou are an ESG (Environmental, Social, and Governance) risk classification expert specialized in analyzing U.S. 10-K filings. Your task is to classify paragraphs from Item 1A (Risk Factors) sections into exactly one of the following 9 categories.\n\nValid category names:\n- Climate Change\n- Natural Capital\n- Pollution & Waste\n- Human Capital\n- Product Liability\n- Community Relations\n- Corporate Governance\n- Business Ethics & Values\n- Non-ESG<|eot_id|><|start_header_id|>user<|end_header_id|>\n\nClassify the following paragraph from a 10-K filing into one of the 9 ESG categories based on the definitions below.\n\n=== CATEGORY DEFINITIONS ===\nClimate Change: This topic includes discussions about carbon emissions or climate change, including initiatives to increase carbon efficiency, environmental technologies, renewable energy, and the development or refurbishment of buildings with leading ecological design features. The following are some examples:\n- We are also excited about our commitment to securing 100% of our purchased electricity from renewable sources by 2025, reducing our operational carbon footprint by 30%.\n- In 2018, we acquired a 43.83% interest in Silicon Ranch, a leading US developer, owner, and operator of solar assets.\n- Beginning in 2012 through the end of 2016, we have converted 19 plants from coal to natural gas or steam.\n- 40% of our operations are to be certified under a green building standard by 2018.\n\nNatural Capital: This topic includes discussions about water stress, biodiversity, land use, and raw materials sourcing. For water stress, we include discussions of how companies manage risks of water shortages, such as by employing efficient water processes, water recycling, and alternative water sources. For biodiversity and land use, we include discussions about programs and policies designed to protect biodiversity and address community land-use concerns. For raw materials sourcing, we include discussions about policies and procedures to source materials with lower environmental impact, such as seafood/aquaculture, timber/paper, palm oil, beef/dairy, leather, and cotton.\n\nPollution & Waste: This topic includes discussions about toxic emissions, packaging materials, and electronic waste. For toxic emissions and waste, we include discussions of pollution, contamination, and emission of toxic and carcinogenic substances and wastewater. For packaging materials and waste, we include discussions of product packaging content and end-of-life recycling or disposal of packaging materials. We include discussions about the recycling and removal of end-of-life electronic products for electronic waste.\n\nHuman Capital: This topic includes discussions about labor management, health and safety, human capital development and training, and supply chain labor standards. For labor management, we include discussions workforce management, risk of workflow disruptions, labor productivity issues, employee diversity, and pay equality (non-executive). For health and safety, we include discussions of employee health and safety (H&S) programs. For human capital development and training, we include discussions of the ability to attract, retain, and develop human capital based on benefits, training, development programs, and employee engagement provided. For supply chain labor standards, we include discussions of supply chain production disruptions and brand value damage due to sub-standard treatment of workers.\n\nProduct Liability: This topic includes discussing product safety and quality, privacy and data security, chemical safety, consumer financial protection, and health and demographic risk. For product safety and quality, we include discussion of product recalls, losing customer trust through product quality concerns. For privacy and data security, we have discussions of data security breaches, the controversial use of personal data. For chemical safety, we include discussions of the use or presence of chemicals of concern. For consumer financial protection, we include discussions of the transparency of financial products. For health and demographic risk, we include discussions of public health trends.\n\nCommunity Relations: This topic includes discussions of a firm\'s interaction with its local communities, including access to communications, access to finance, and access to healthcare. We include discussions about opportunities in historically underserved markets, such as developing countries and underserved populations, and relevant philanthropic efforts.\n\nCorporate Governance: This topic includes discussions on shareholders and ownership, board of directors, executive pay, and internal controls. For shareholders and ownership, we include discussions regarding ownership structure, control structure, and shareholders. For the board of directors, we include discussions of the board\'s independence from management, board skills and diversity, and board effectiveness. For executive pay, we include CEO and other executives\' pay practices. For internal control, we consider internal controls, audit matters, and internal audit matters.\n\nBusiness Ethics & Values: This topic includes discussions about ethical components such as a firm\'s values and controversies. We include discussions about the ethical conduct of business, fraud, corruption, bribery, fiduciary responsibilities, conflicts of interest, misrepresentation, bias, negligence, political contributions, negative accounting events, and other behaviors which may have ethical components.\n\nNon-ESG: The paragraph does not primarily discuss any of the above ESG topics. Typical Non-ESG content includes: general financial performance, revenue/earnings discussions, market competition, product/service descriptions, operational logistics, legal boilerplate, accounting policies, and general business strategy unrelated to ESG.\n\n=== IMPORTANT RULES ===\n- Choose the SINGLE most relevant category.\n- Only classify as an ESG category if the paragraph PRIMARILY discusses that topic.\n- If uncertain between an ESG category and Non-ESG, lean toward Non-ESG.\n\n=== PARAGRAPH TO CLASSIFY ===\nRisks Related to Government Regulations\nThere has been, and likely will continue to be, increased regulation with respect to the collection, use and handling of an individual’s personal and financial information. Regulatory authorities around the world have passed or are considering legislative and regulatory proposals concerning data protection, privacy and data security. In the United States, Virginia and Colorado passed new comprehensive privacy legislation, and joined California (which further enhanced its existing privacy laws) in directly regulating the collection, use and sharing of personal information. These statutes create civil penalties for violations, and in the case of California, creates a private right of action for data breaches, that increases the risk of data breach litigation. Absent a pre-emptive Federal privacy law, as more states pass privacy legislation, there is a strong possibility that we will be forced to comply with a patchwork of inconsistent privacy regulations. Globally, personal information collected within the European Union and United Kingdom remains subject to the 2018 General Data Protection Regulation (GDPR), which is a UK and European Union-wide legal framework that governs data collection, use, and sharing of an individual’s personal data and creates a range of consumer privacy rights. GDPR provides significant penalties for non-compliance (up to 4% of global revenue) and EU data protection authorities have already issued significant fines. Similarly, in November 2021, China promulgated the Personal Information Protection Law (PIPL) which regulates the processing of personal information of individuals within China. If a company breaches PIPL it can be assessed fines of up 5% of its annual revenue. The interpretation and application of consumer and data protection laws and industry standards in the United States, Europe, China and elsewhere can be uncertain and currently is in flux.<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\n<reasoning>\nKey keywords and concepts in the paragraph include "collection, use and handling of an individual’s personal and financial information," "data protection, privacy and data security," "data breach litigation," "civil penalties," and references to GDPR, PIPL, and state privacy laws. These concepts map to the Product Liability definition because it explicitly includes privacy and data security risks and regulatory penalties for breaches of consumer data protection. Other ESG categories like Corporate Governance or Business Ethics could touch on compliance but do not focus on consumer data privacy and breach liabilities, and Climate Change, Natural Capital, Pollution & Waste, Human Capital, and Community Relations are not relevant to data protection.\n</reasoning>\n<label>Product Liability</label><|eot_id|>'

<a name="Train"></a>
### Train the model
Now let's train our model. We do 60 steps to speed things up, but you can set `num_train_epochs=1` for a full run, and turn off `max_steps=None`. We also support `DPOTrainer` and `GRPOTrainer` for reinforcement learning!!

In [8]:
from trl import SFTConfig, SFTTrainer
from transformers import DataCollatorForSeq2Seq
trainer = SFTTrainer(
  model = model,
  tokenizer = tokenizer,
  train_dataset = dataset,
  dataset_text_field = "text",
  max_seq_length = max_seq_length,
  data_collator = DataCollatorForSeq2Seq(tokenizer = tokenizer),
  packing = False, # Can make training 5x faster for short sequences.
  args = SFTConfig(
    per_device_train_batch_size = 2,
    gradient_accumulation_steps = 4,
    warmup_steps = 5,
    num_train_epochs = 1, # Set this for 1 full training run.
    # max_steps = 200,
    learning_rate = 2e-4,
    logging_steps = 1,
    optim = "adamw_8bit",
    weight_decay = 0.001,
    lr_scheduler_type = "linear",
    seed = 3407,
    output_dir = "outputs",
    report_to = "none", # Use TrackIO/WandB etc
  ),
)

We also use Unsloth's `train_on_completions` method to only train on the assistant outputs and ignore the loss on the user's inputs.

In [9]:
from unsloth.chat_templates import train_on_responses_only
trainer = train_on_responses_only(
  trainer,
  instruction_part = "<|start_header_id|>user<|end_header_id|>\n\n",
  response_part = "<|start_header_id|>assistant<|end_header_id|>\n\n",
)

We verify masking is actually done:

In [10]:
tokenizer.decode(trainer.train_dataset[5]["input_ids"])

'<|begin_of_text|><|begin_of_text|><|start_header_id|>system<|end_header_id|>\n\nCutting Knowledge Date: December 2023\nToday Date: 26 July 2024\n\nYou are an ESG (Environmental, Social, and Governance) risk classification expert specialized in analyzing U.S. 10-K filings. Your task is to classify paragraphs from Item 1A (Risk Factors) sections into exactly one of the following 9 categories.\n\nValid category names:\n- Climate Change\n- Natural Capital\n- Pollution & Waste\n- Human Capital\n- Product Liability\n- Community Relations\n- Corporate Governance\n- Business Ethics & Values\n- Non-ESG<|eot_id|><|start_header_id|>user<|end_header_id|>\n\nClassify the following paragraph from a 10-K filing into one of the 9 ESG categories based on the definitions below.\n\n=== CATEGORY DEFINITIONS ===\nClimate Change: This topic includes discussions about carbon emissions or climate change, including initiatives to increase carbon efficiency, environmental technologies, renewable energy, and the development or refurbishment of buildings with leading ecological design features. The following are some examples:\n- We are also excited about our commitment to securing 100% of our purchased electricity from renewable sources by 2025, reducing our operational carbon footprint by 30%.\n- In 2018, we acquired a 43.83% interest in Silicon Ranch, a leading US developer, owner, and operator of solar assets.\n- Beginning in 2012 through the end of 2016, we have converted 19 plants from coal to natural gas or steam.\n- 40% of our operations are to be certified under a green building standard by 2018.\n\nNatural Capital: This topic includes discussions about water stress, biodiversity, land use, and raw materials sourcing. For water stress, we include discussions of how companies manage risks of water shortages, such as by employing efficient water processes, water recycling, and alternative water sources. For biodiversity and land use, we include discussions about programs and policies designed to protect biodiversity and address community land-use concerns. For raw materials sourcing, we include discussions about policies and procedures to source materials with lower environmental impact, such as seafood/aquaculture, timber/paper, palm oil, beef/dairy, leather, and cotton.\n\nPollution & Waste: This topic includes discussions about toxic emissions, packaging materials, and electronic waste. For toxic emissions and waste, we include discussions of pollution, contamination, and emission of toxic and carcinogenic substances and wastewater. For packaging materials and waste, we include discussions of product packaging content and end-of-life recycling or disposal of packaging materials. We include discussions about the recycling and removal of end-of-life electronic products for electronic waste.\n\nHuman Capital: This topic includes discussions about labor management, health and safety, human capital development and training, and supply chain labor standards. For labor management, we include discussions workforce management, risk of workflow disruptions, labor productivity issues, employee diversity, and pay equality (non-executive). For health and safety, we include discussions of employee health and safety (H&S) programs. For human capital development and training, we include discussions of the ability to attract, retain, and develop human capital based on benefits, training, development programs, and employee engagement provided. For supply chain labor standards, we include discussions of supply chain production disruptions and brand value damage due to sub-standard treatment of workers.\n\nProduct Liability: This topic includes discussing product safety and quality, privacy and data security, chemical safety, consumer financial protection, and health and demographic risk. For product safety and quality, we include discussion of product recalls, losing customer trust through product quality concerns. For privacy and data security, we have discussions of data security breaches, the controversial use of personal data. For chemical safety, we include discussions of the use or presence of chemicals of concern. For consumer financial protection, we include discussions of the transparency of financial products. For health and demographic risk, we include discussions of public health trends.\n\nCommunity Relations: This topic includes discussions of a firm\'s interaction with its local communities, including access to communications, access to finance, and access to healthcare. We include discussions about opportunities in historically underserved markets, such as developing countries and underserved populations, and relevant philanthropic efforts.\n\nCorporate Governance: This topic includes discussions on shareholders and ownership, board of directors, executive pay, and internal controls. For shareholders and ownership, we include discussions regarding ownership structure, control structure, and shareholders. For the board of directors, we include discussions of the board\'s independence from management, board skills and diversity, and board effectiveness. For executive pay, we include CEO and other executives\' pay practices. For internal control, we consider internal controls, audit matters, and internal audit matters.\n\nBusiness Ethics & Values: This topic includes discussions about ethical components such as a firm\'s values and controversies. We include discussions about the ethical conduct of business, fraud, corruption, bribery, fiduciary responsibilities, conflicts of interest, misrepresentation, bias, negligence, political contributions, negative accounting events, and other behaviors which may have ethical components.\n\nNon-ESG: The paragraph does not primarily discuss any of the above ESG topics. Typical Non-ESG content includes: general financial performance, revenue/earnings discussions, market competition, product/service descriptions, operational logistics, legal boilerplate, accounting policies, and general business strategy unrelated to ESG.\n\n=== IMPORTANT RULES ===\n- Choose the SINGLE most relevant category.\n- Only classify as an ESG category if the paragraph PRIMARILY discusses that topic.\n- If uncertain between an ESG category and Non-ESG, lean toward Non-ESG.\n\n=== PARAGRAPH TO CLASSIFY ===\nRisks Related to Government Regulations\nThere has been, and likely will continue to be, increased regulation with respect to the collection, use and handling of an individual’s personal and financial information. Regulatory authorities around the world have passed or are considering legislative and regulatory proposals concerning data protection, privacy and data security. In the United States, Virginia and Colorado passed new comprehensive privacy legislation, and joined California (which further enhanced its existing privacy laws) in directly regulating the collection, use and sharing of personal information. These statutes create civil penalties for violations, and in the case of California, creates a private right of action for data breaches, that increases the risk of data breach litigation. Absent a pre-emptive Federal privacy law, as more states pass privacy legislation, there is a strong possibility that we will be forced to comply with a patchwork of inconsistent privacy regulations. Globally, personal information collected within the European Union and United Kingdom remains subject to the 2018 General Data Protection Regulation (GDPR), which is a UK and European Union-wide legal framework that governs data collection, use, and sharing of an individual’s personal data and creates a range of consumer privacy rights. GDPR provides significant penalties for non-compliance (up to 4% of global revenue) and EU data protection authorities have already issued significant fines. Similarly, in November 2021, China promulgated the Personal Information Protection Law (PIPL) which regulates the processing of personal information of individuals within China. If a company breaches PIPL it can be assessed fines of up 5% of its annual revenue. The interpretation and application of consumer and data protection laws and industry standards in the United States, Europe, China and elsewhere can be uncertain and currently is in flux.<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\n<reasoning>\nKey keywords and concepts in the paragraph include "collection, use and handling of an individual’s personal and financial information," "data protection, privacy and data security," "data breach litigation," "civil penalties," and references to GDPR, PIPL, and state privacy laws. These concepts map to the Product Liability definition because it explicitly includes privacy and data security risks and regulatory penalties for breaches of consumer data protection. Other ESG categories like Corporate Governance or Business Ethics could touch on compliance but do not focus on consumer data privacy and breach liabilities, and Climate Change, Natural Capital, Pollution & Waste, Human Capital, and Community Relations are not relevant to data protection.\n</reasoning>\n<label>Product Liability</label><|eot_id|>'

In [11]:
space = tokenizer(" ", add_special_tokens = False).input_ids[0]
tokenizer.decode([space if x == -100 else x for x in trainer.train_dataset[5]["labels"]])

'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           <reasoning>\nKey keywords and concepts in the paragraph include "collection, use and handling of an individual’s personal and financial information," "data protection, privacy and data security," "data breach litigation," "civil penalties," and references to GDPR, PIPL, and state privacy laws. These concepts map to the Product Liability definition because it explicitly includes privacy and data security risks and regulatory penalties for breaches of consumer data protection. Other ESG categories like Corporate Governance or Business Ethics could touch on compliance but do not focus on consumer data privacy and breach liabilities, and Climate Change, Natural Capital, Pollution & Waste, Human Capital, and Community Relations are not relevant to data protection.\n</reasoning>\n<label>Product Liability</label><|eot_id|>'

We can see the System and Instruction prompts are successfully masked!

In [12]:
# @title Show current memory stats
gpu_stats = torch.cuda.get_device_properties(0)
start_gpu_memory = round(torch.cuda.max_memory_reserved() / 1024 / 1024 / 1024, 3)
max_memory = round(gpu_stats.total_memory / 1024 / 1024 / 1024, 3)
print(f"GPU = {gpu_stats.name}. Max memory = {max_memory} GB.")
print(f"{start_gpu_memory} GB of memory reserved.")

GPU = NVIDIA GeForce RTX 4090. Max memory = 23.518 GB.
2.359 GB of memory reserved.

In [13]:
trainer_stats = trainer.train()

==((====))== Unsloth - 2x faster free finetuning | Num GPUs used = 1
  \\  /|  Num examples = 779 | Num Epochs = 1 | Total steps = 98
O^O/ \_/ \  Batch size per device = 2 | Gradient accumulation steps = 4
\    /  Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"   Trainable parameters = 24,313,856 of 3,237,063,680 (0.75% trained)

In [14]:
# @title Show final memory and time stats
used_memory = round(torch.cuda.max_memory_reserved() / 1024 / 1024 / 1024, 3)
used_memory_for_lora = round(used_memory - start_gpu_memory, 3)
used_percentage = round(used_memory / max_memory * 100, 3)
lora_percentage = round(used_memory_for_lora / max_memory * 100, 3)
print(f"{trainer_stats.metrics['train_runtime']} seconds used for training.")
print(
  f"{round(trainer_stats.metrics['train_runtime']/60, 2)} minutes used for training."
)
print(f"Peak reserved memory = {used_memory} GB.")
print(f"Peak reserved memory for training = {used_memory_for_lora} GB.")
print(f"Peak reserved memory % of max memory = {used_percentage} %.")
print(f"Peak reserved memory for training % of max memory = {lora_percentage} %.")

268.507 seconds used for training.
4.48 minutes used for training.
Peak reserved memory = 8.643 GB.
Peak reserved memory for training = 6.284 GB.
Peak reserved memory % of max memory = 36.751 %.
Peak reserved memory for training % of max memory = 26.72 %.

<a name="Inference"></a>
### Inference
Let's run the model! You can change the instruction and input - leave the output blank!



We use `min_p = 0.1` and `temperature = 1.5`. Read this [Tweet](https://x.com/menhguin/status/1826132708508213629) for more information on why.

In [15]:
# from unsloth.chat_templates import get_chat_template

# tokenizer = get_chat_template(
#   tokenizer,
#   chat_template = "llama-3.1",
# )
# FastLanguageModel.for_inference(model) # Enable native 2x faster inference

# messages = [
#   {"role": "user", "content": "Continue the fibonacci sequence: 1, 1, 2, 3, 5, 8,"},
# ]
# inputs = tokenizer.apply_chat_template(
#   messages,
#   tokenize = True,
#   add_generation_prompt = True, # Must add for generation
#   return_tensors = "pt",
# ).to("cuda")

# outputs = model.generate(input_ids = inputs, max_new_tokens = 64, use_cache = True,
#             temperature = 1.5, min_p = 0.1)
# tokenizer.batch_decode(outputs)

 You can also use a `TextStreamer` for continuous inference - so you can see the generation token by token, instead of waiting the whole time!

In [16]:
# FastLanguageModel.for_inference(model) # Enable native 2x faster inference

# messages = [
#   {"role": "user", "content": "Continue the fibonacci sequence: 1, 1, 2, 3, 5, 8,"},
# ]
# inputs = tokenizer.apply_chat_template(
#   messages,
#   tokenize = True,
#   add_generation_prompt = True, # Must add for generation
#   return_tensors = "pt",
# ).to("cuda")

# from transformers import TextStreamer
# text_streamer = TextStreamer(tokenizer, skip_prompt = True)
# _ = model.generate(input_ids = inputs, streamer = text_streamer, max_new_tokens = 128,
#          use_cache = True, temperature = 1.5, min_p = 0.1)

In [17]:
SYSTEM_PROMPT = """You are an ESG (Environmental, Social, and Governance) risk classification expert specialized in analyzing U.S. 10-K filings. Your task is to classify paragraphs from Item 1A (Risk Factors) sections into exactly one of the following 9 categories.

You must respond with ONLY the category name. Do not include any explanation, reasoning, numbering, or additional text.

Valid category names (respond with one of these exactly):
- Climate Change
- Natural Capital
- Pollution & Waste
- Human Capital
- Product Liability
- Community Relations
- Corporate Governance
- Business Ethics & Values
- Non-ESG

CRITICAL: Your entire response must be EXACTLY one of the 9 category names above. No other words, punctuation, or characters. Maximum 4 words."""

USER_PROMPT_TEMPLATE = """Classify the following paragraph from a 10-K filing into one of the 9 ESG categories based on the definitions and examples below.

=== CATEGORY DEFINITIONS ===

Appendix: Detail description and examples of the eight ESG topics:
Climate Change: This topic includes discussions about carbon emissions or climate change, including
initiatives to increase carbon efficiency, environmental technologies, renewable energy, and the
development or refurbishment of buildings with leading ecological design features. The following are
some examples:
- We are also excited about our commitment to securing 100% of our purchased electricity from
renewable sources by 2025, reducing our operational carbon footprint by 30%.
- In 2018, we acquired a 43.83% interest in Silicon Ranch, a leading US developer, owner, and
operator of solar assets. In 2019, Silicon Ranch announced the launch of a program that
combines clean electricity generation with carbon sequestration and ecosystem restoration.
- Beginning in 2012 through the end of 2016, we have converted 19 plants from coal to natural
gas or steam.
- 40% of our operations are to be certified under a green building standard by 2018.
Natural Capital: This topic includes discussions about water stress, biodiversity, land use, and raw
materials sourcing. For water stress, we include discussions of how companies manage risks of water
shortages, such as by employing efficient water processes, water recycling, and alternative water
sources. For biodiversity and land use, we include discussions about programs and policies designed to
protect biodiversity and address community land-use concerns. For raw materials sourcing, we include
discussions about policies and procedures to source materials with lower environmental impact, such
as seafood/aquaculture, timber/paper, palm oil, beef/dairy, leather, and cotton. The following are some
examples:
- This year, we continued Stella Artois' Buy a Lady a Drink program with Water.org, which aims
to tackle the global water crisis. Having to date supported nearly 800,000 people, we recently
announced our ambition to provide access to safe water to 3.5 million people in the developing
world by 2020.
- At the chemical complex in the Netherlands, our biodiversity action plan has helped maintain a
variety of flora and fauna. It has also raised awareness about biodiversity among technical
staff. For example, in 2019, planned maintenance work was adjusted after operators found a
protected bird species nesting in equipment.
- 100% of the paper used in our U.S direct marketing efforts was certified to be from sustainably
managed forests.
- During the period, Kimco remediated soil as a part of major development or redevelopment
projects at the following locations: Dania Pointe (Dania Beach, FL), Suburban Square
(Ardmore, PA), Lincoln Square (Philadelphia, PA).
Pollution and Waste: This topic includes discussions about toxic emissions, packaging materials, and
electronic waste. For toxic emissions and waste, we include discussions of pollution, contamination,
and emission of toxic and carcinogenic substances and wastewater. For packaging materials and waste,
we include discussions of product packaging content and end-of-life recycling or disposal of
packaging materials. We include discussions about the recycling and removal of end-of-life electronic
products for electronic waste. The following are some examples:
- We also have programs in place to reduce the number of operational spills over the long term.
In 2019, we continued to carry out vital work to clean up Bodo, an area badly affected by oil
spills.
- Through lightweighting and packaging reduction initiatives, we have reduced the amount of
packaging we use by 126,800 tons since 2012, exceeding our 2017 reduction goal of 100,000
tons a year early.
- All of these programs reduce waste and encourage reuse by ensuring that valuable products
can go back into the hands of customers rather than being sent to landfills.
- Several years ago, we saw an opportunity to create a single streamlined solution for tenants
that could provide them with more reliable and cost-effective waste services.
Human Capital: This topic includes discussions about labor management, health and safety, human
capital development and training, and supply chain labor standards. For labor management, we include
discussions workforce management, risk of workflow disruptions, labor productivity issues, employee
diversity, and pay equality (non-executive). For health and safety, we include discussions of employee
health and safety (H&S) programs such as H&S policies and their implementations, H&S training, and
safety certifications. For human capital development and training, we include discussions of the ability
to attract, retain, and develop human capital based on benefits, training, development programs, and
employee engagement provided. For supply chain labor standards, we include discussions of supply
chain production disruptions and brand value damage due to sub-standard treatment of workers in the
company's supply chain or reliance on raw materials that originate in areas associated with severe
human rights and labor rights issues (e.g., slave labor and child labor). The following are some
examples:
- We provide formal channels to guide colleagues and leaders on decisions related to flextime,
part-time, compressed work weeks, job sharing, and remote work.
- We use technology systems on our trucks to track driver behaviors, which has increased
accountability among our managers and resulted in a reduction in speeding and safer fleet
operations.
- Enterprise Leadership delivers targeted leadership development programs to colleagues at
specific stages of their careers.
- This can lead to unfair treatment of workers, which is why we continue our efforts to source
secondary raw materials in a way that's aligned with our "Fair and Equal" agenda.
Product Liability: This topic includes discussing product safety and quality, privacy and data
security, chemical safety, consumer financial protection, and health and demographic risk. For product
safety and quality, we include discussion of product recalls, losing customer trust through product
quality concerns, or product safety and quality certifications. For privacy and data security, we have
discussions of data security breaches, the controversial use of personal data, and company data privacy
policies and data security management systems. For chemical safety, we include discussions of the use
or presence of chemicals of concern and procedures relating to chemical safety and its impact on
customers. For consumer financial protection, we include discussions of the transparency of financial
products based on borrowers' ability to repay and initiatives to protect customers through product
transparency. For health and demographic risk, we include discussions of public health trends and
demographic changes, growth opportunities in the market for healthier products, and improved
nutritional profiles. The following are some examples:
- Our products are designed and tested to comply with all applicable safety regulations in the
countries where the products are sold.
- Information Security oversees a comprehensive program to help predict, protect, detect,
respond to, and recover from cyberattacks.
- For example, we have phased out any chemicals suspected of causing medical reactions or
harm.
- The Smarter CreditTM Center includes resources to help customers understand, build, and
improve credit, as well as manage debt and plan for large purchases.
Community Relations: This topic includes discussions of a firm's interaction with its local
communities, including access to communications, access to finance, and access to healthcare. We
include discussions about opportunities in historically underserved markets, such as developing
countries and underserved populations, and relevant philanthropic efforts. The following are some
examples:
- We've gone from sourcing 70% of barley locally in 2014 to 86% in 2016, and we're on track to
achieve 100% local sourcing by 2017.
- In addition, we have committed to a package of public interest commitments, which include a
commitment to invest 1 billion ZAR in areas including supporting smallholder farmers and
enterprise development.
- We aim to improve access for local people to health care and treatments for diseases such as
cancer.
- Participants volunteer for significant causes such as disaster relief, hunger, medical research,
home building or youth mentoring, and groups are encouraged to serve together as a means of
multiplying their impact and fostering team spirit.
Corporate Governance: This topic includes discussions on shareholders and ownership, board of
directors, executive pay, and internal controls. For shareholders and ownership, we include discussions
regarding ownership structure, control structure, and shareholders. For the board of directors, we
include discussions of the board's independence from management, board skills and diversity, and
board effectiveness. For executive pay, we include CEO and other executives' pay practices and 
specific pay figures, performance incentives, and overall pay plan design. For internal control, we
consider internal controls, audit matters, audit committee matters, and internal audit matters. The
following are some examples:
- Based on filings made under Sections 13(d) and 13(g) of the Securities Exchange Act of 1934,
as amended, as of December 31, 2020, the only persons or entities known by us to be a
beneficial owner of more than 5% of our common stock were as follows.
- Our Board is composed entirely of independent directors other than our chairman and CEO,
and is diverse, with diversity reflecting gender, age, race, ethnicity, background, professional
experience, and perspectives.
- We announced plans in 2018 to link executive remuneration to short-term targets to reduce the
Net Carbon Footprint of the energy products we sell, including our customers' emissions from
their use of our energy products.
- The appointment by the Audit and Compliance Committee of the Company's Board of
Directors of PricewaterhouseCoopers LLP, as an independent registered public accounting
firm for the Company, to audit the financial statements of the Company and its subsidiaries for
2022 is hereby ratified and approved.
Business Ethics and Values: This topic includes discussions about ethical components such as a
firm's values and controversies. We include discussions about the ethical conduct of business, fraud,
corruption, bribery, fiduciary responsibilities, conflicts of interest, misrepresentation, bias, negligence,
political contributions, negative accounting events, and other behaviors which may have ethical
components. The following is an example:
- At the heart of our culture is what we call our Blue Box Values - a set of seven guiding
principles that every employee pledges to embrace and work by each day.
- Huntington is dedicated to uncompromising integrity in all that it does and how it relates to its
internal colleagues and to persons outside Huntington.
- In reaching this settlement, we neither admitted nor denied the claims in the order and agreed
to pay a civil monetary penalty of $5.5 million.
- In addition, certain private parties as well as state attorneys general and other antitrust
authorities may challenge the transactions under U.S. or foreign antitrust laws under certain
circumstances.

Non-ESG
The paragraph does not primarily discuss any of the above ESG topics. Typical Non-ESG content includes: general financial performance, revenue/earnings discussions, market competition, product/service descriptions, operational logistics, legal boilerplate, accounting policies, and general business strategy unrelated to ESG.

=== IMPORTANT RULES ===
- Choose the SINGLE most relevant category. If a paragraph touches multiple ESG topics, select the PRIMARY one.
- Only classify as an ESG category if the paragraph PRIMARILY discusses that topic. Incidental mentions do not qualify.
- If uncertain between an ESG category and Non-ESG, lean toward Non-ESG.
- Respond with ONLY the category name, nothing else.

=== PARAGRAPH TO CLASSIFY ===
{text}

Remember: Output ONLY the category name. One of the 9 valid labels. No explanation. No punctuation. Maximum 4 words."""

<a name="Evaluation"></a>
### Model Evaluation
Let's evaluate the model on the validation dataset and calculate metrics including F1 score, accuracy, precision, and recall.

In [18]:
import json
import pandas as pd

TEST_PATH = "../../data/processed/step3_annotation/test_labeled.json"

with open(TEST_PATH, "r", encoding="utf-8") as f:
  test_data = json.load(f)

test_df = pd.DataFrame(test_data)

print("Test size:", len(test_df))
print(test_df[["paragraph_id", "combined_text", "label"]].head())

Test size: 200
    paragraph_id                   combined_text \
0 SPG_2022_RISK_015 Risks Relating to Retail Operations\nIf a depa...
1 TYL_2022_RISK_032 Risks Related to Our Indebtedness\nBank Nation...
2 FRT_2022_RISK_043 We face risks relating to cyber attacks that c...
3 DHI_2021_RISK_063 General Risk Factors\nWe may also be required ...
4 AMT_2022_RISK_051 Risks Related to the Operation of Our Business...

        label
0      Non-ESG
1      Non-ESG
2 Product Liability
3 Product Liability
4 Product Liability

In [19]:
import re
import torch
import pandas as pd
from IPython.display import display
from tqdm import tqdm
from sklearn.metrics import (
  accuracy_score,
  precision_recall_fscore_support,
  classification_report,
  confusion_matrix,
)

LABELS = [
  "Climate Change",
  "Natural Capital",
  "Pollution & Waste",
  "Human Capital",
  "Product Liability",
  "Community Relations",
  "Corporate Governance",
  "Business Ethics & Values",
  "Non-ESG",
]

LABELS_SORTED = sorted(LABELS, key=len, reverse=True)
INVALID_LABEL = "__INVALID__"


def normalize_label(text):
  if text is None:
    return None

  text = re.sub(r"\s+", " ", str(text)).strip()
  if not text:
    return None

  for label in LABELS_SORTED:
    if text == label or text.startswith(label):
      return label

  patterns = [
    r"(?i)(?:answer|label|category)\s*:\s*(.+)$",
    r"(?i)(?:classified as|category is|label is)\s*:?\s*(.+)$",
    r"(?i)(?:the correct category is)\s*:?\s*(.+)$",
  ]
  for pattern in patterns:
    match = re.search(pattern, text)
    if match:
      candidate = match.group(1).strip()
      for label in LABELS_SORTED:
        if candidate == label or candidate.startswith(label):
          return label

  tail = text[-200:]
  matched = [label for label in LABELS_SORTED if re.search(rf"(?i)\b{re.escape(label)}\b", tail)]
  if len(matched) == 1:
    return matched[0]

  matched = [label for label in LABELS_SORTED if re.search(rf"(?i)\b{re.escape(label)}\b", text)]
  matched = list(dict.fromkeys(matched))
  if len(matched) == 1:
    return matched[0]

  return None


def build_messages(paragraph_text):
  return [
    {"role": "system", "content": SYSTEM_PROMPT},
    {
      "role": "user",
      "content": USER_PROMPT_TEMPLATE.replace("{text}", paragraph_text),
    },
  ]


def prepare_inputs(messages):
  tokenized = tokenizer.apply_chat_template(
    messages,
    tokenize=True,
    add_generation_prompt=True,
    return_tensors="pt",
  )

  if isinstance(tokenized, torch.Tensor):
    input_ids = tokenized.to("cuda")
    attention_mask = torch.ones_like(input_ids)
  else:
    input_ids = tokenized["input_ids"].to("cuda")
    attention_mask = tokenized.get("attention_mask", torch.ones_like(input_ids)).to("cuda")

  return {"input_ids": input_ids, "attention_mask": attention_mask}


FastLanguageModel.for_inference(model)

y_true_parseable = []
y_pred_parseable = []
y_true_all = []
y_pred_all = []
failed_cases = []

print(f"Evaluating on {len(test_df)} test samples...\n")

for _, row in tqdm(test_df.iterrows(), total=len(test_df), desc="Evaluating"):
  paragraph_id = row.get("paragraph_id")
  paragraph_text = row["combined_text"]
  gt_label = normalize_label(row["label"])

  if gt_label is None:
    failed_cases.append({
      "paragraph_id": paragraph_id,
      "reason": "invalid_ground_truth",
      "ground_truth": row.get("label"),
    })
    continue

  y_true_all.append(gt_label)

  try:
    messages = build_messages(paragraph_text)
    inputs = prepare_inputs(messages)

    with torch.no_grad():
      outputs = model.generate(
        **inputs,
        max_new_tokens=24,
        do_sample=False,
        temperature=None,
        top_p=None,
        use_cache=True,
        pad_token_id=tokenizer.eos_token_id,
      )

    prompt_len = inputs["input_ids"].shape[1]
    decoded = tokenizer.decode(outputs[0][prompt_len:], skip_special_tokens=True).strip()
    pred_label = normalize_label(decoded)

    if len(y_pred_all) < 5:
      print("RAW OUTPUT:", repr(decoded))
      print("PARSED PRED:", pred_label)
      print("GT:", gt_label)
      print("-" * 80)

    if pred_label is None:
      y_pred_all.append(INVALID_LABEL)
      failed_cases.append({
        "paragraph_id": paragraph_id,
        "reason": "prediction_parse_failed",
        "ground_truth": gt_label,
        "raw_output": decoded,
      })
      continue

    y_true_parseable.append(gt_label)
    y_pred_parseable.append(pred_label)
    y_pred_all.append(pred_label)

  except Exception as exc:
    y_pred_all.append(INVALID_LABEL)
    failed_cases.append({
      "paragraph_id": paragraph_id,
      "reason": "exception",
      "ground_truth": gt_label,
      "error": str(exc),
    })

total_eval = len(y_true_all)
num_parseable = len(y_true_parseable)
num_failed = len(failed_cases)
parse_fail_rate = num_failed / total_eval if total_eval else 0.0

print("\n=== Evaluation Summary ===")
print(f"Total evaluated samples: {total_eval}")
print(f"Parseable predictions:  {num_parseable}")
print(f"Failed predictions:   {num_failed}")
print(f"Parse failure rate:   {parse_fail_rate:.4f}")

print("\n" + "=" * 70)
print("PARSEABLE-ONLY METRICS")
print("=" * 70)

if y_true_parseable:
  acc_p = accuracy_score(y_true_parseable, y_pred_parseable)
  macro_p_p, macro_r_p, macro_f1_p, _ = precision_recall_fscore_support(
    y_true_parseable,
    y_pred_parseable,
    labels=LABELS,
    average="macro",
    zero_division=0,
  )
  weighted_p_p, weighted_r_p, weighted_f1_p, _ = precision_recall_fscore_support(
    y_true_parseable,
    y_pred_parseable,
    labels=LABELS,
    average="weighted",
    zero_division=0,
  )

  print(f"Accuracy:      {acc_p:.4f}")
  print(f"Macro Precision:   {macro_p_p:.4f}")
  print(f"Macro Recall:    {macro_r_p:.4f}")
  print(f"Macro F1:      {macro_f1_p:.4f}")
  print(f"Weighted Precision: {weighted_p_p:.4f}")
  print(f"Weighted Recall:   {weighted_r_p:.4f}")
  print(f"Weighted F1:     {weighted_f1_p:.4f}")

  print("\n=== Classification Report (Parseable-only) ===")
  print(classification_report(y_true_parseable, y_pred_parseable, labels=LABELS, zero_division=0))

  cm_parseable = confusion_matrix(y_true_parseable, y_pred_parseable, labels=LABELS)
  display(pd.DataFrame(cm_parseable, index=LABELS, columns=LABELS))
else:
  print("No parseable predictions available.")

print("\n" + "=" * 70)
print("END-TO-END METRICS (failed outputs counted as wrong)")
print("=" * 70)

if y_true_all:
  acc_all = accuracy_score(y_true_all, y_pred_all)
  macro_p_all, macro_r_all, macro_f1_all, _ = precision_recall_fscore_support(
    y_true_all,
    y_pred_all,
    labels=LABELS,
    average="macro",
    zero_division=0,
  )
  weighted_p_all, weighted_r_all, weighted_f1_all, _ = precision_recall_fscore_support(
    y_true_all,
    y_pred_all,
    labels=LABELS,
    average="weighted",
    zero_division=0,
  )

  print(f"Accuracy:      {acc_all:.4f}")
  print(f"Macro Precision:   {macro_p_all:.4f}")
  print(f"Macro Recall:    {macro_r_all:.4f}")
  print(f"Macro F1:      {macro_f1_all:.4f}")
  print(f"Weighted Precision: {weighted_p_all:.4f}")
  print(f"Weighted Recall:   {weighted_r_all:.4f}")
  print(f"Weighted F1:     {weighted_f1_all:.4f}")

  print("\n=== Classification Report (End-to-end) ===")
  print(classification_report(y_true_all, y_pred_all, labels=LABELS, zero_division=0))

  cm_all_labels = LABELS + [INVALID_LABEL]
  cm_all = confusion_matrix(y_true_all, y_pred_all, labels=cm_all_labels)
  print("\n=== Confusion Matrix (End-to-end) ===")
  print("Rows = ground truth, Columns = prediction")
  display(pd.DataFrame(cm_all, index=cm_all_labels, columns=cm_all_labels))

  invalid_pred_count = sum(pred == INVALID_LABEL for pred in y_pred_all)
  print(f"\nInvalid prediction count: {invalid_pred_count}")
else:
  print("No end-to-end samples available.")

if failed_cases:
  failed_df = pd.DataFrame(failed_cases)
  print("\n=== Failed Cases by Reason ===")
  display(failed_df["reason"].value_counts().rename_axis("reason").reset_index(name="count"))
  print("\n=== Failed Cases (head 20) ===")
  display(failed_df.head(20))

Evaluating on 200 test samples...

Evaluating:  0%|     | 0/200 [00:00<?, ?it/s]--- Logging error ---
Traceback (most recent call last):
 File "/home/wa1ter/.local/share/uv/python/cpython-3.11.14-linux-x86_64-gnu/lib/python3.11/logging/__init__.py", line 1110, in emit
  msg = self.format(record)
     ^^^^^^^^^^^^^^^^^^^
 File "/home/wa1ter/.local/share/uv/python/cpython-3.11.14-linux-x86_64-gnu/lib/python3.11/logging/__init__.py", line 953, in format
  return fmt.format(record)
      ^^^^^^^^^^^^^^^^^^
 File "/home/wa1ter/.local/share/uv/python/cpython-3.11.14-linux-x86_64-gnu/lib/python3.11/logging/__init__.py", line 687, in format
  record.message = record.getMessage()
           ^^^^^^^^^^^^^^^^^^^
 File "/home/wa1ter/.local/share/uv/python/cpython-3.11.14-linux-x86_64-gnu/lib/python3.11/logging/__init__.py", line 377, in getMessage
  msg = msg % self.args
     ~~~~^~~~~~~~~~~
TypeError: not all arguments converted during string formatting
Call stack:
 File "/home/wa1ter/.local/share/uv/python/cpython-3.11.14-linux-x86_64-gnu/lib/python3.11/runpy.py", line 198, in _run_module_as_main
  return _run_code(code, main_globals, None,
 File "/home/wa1ter/.local/share/uv/python/cpython-3.11.14-linux-x86_64-gnu/lib/python3.11/runpy.py", line 88, in _run_code
  exec(code, run_globals)
 File "/home/wa1ter/ESG-sft/.venv/lib/python3.11/site-packages/ipykernel_launcher.py", line 18, in <module>
  app.launch_new_instance()
 File "/home/wa1ter/ESG-sft/.venv/lib/python3.11/site-packages/traitlets/config/application.py", line 1075, in launch_instance
  app.start()
 File "/home/wa1ter/ESG-sft/.venv/lib/python3.11/site-packages/ipykernel/kernelapp.py", line 758, in start
  self.io_loop.start()
 File "/home/wa1ter/ESG-sft/.venv/lib/python3.11/site-packages/tornado/platform/asyncio.py", line 211, in start
  self.asyncio_loop.run_forever()
 File "/home/wa1ter/.local/share/uv/python/cpython-3.11.14-linux-x86_64-gnu/lib/python3.11/asyncio/base_events.py", line 608, in run_forever
  self._run_once()
 File "/home/wa1ter/.local/share/uv/python/cpython-3.11.14-linux-x86_64-gnu/lib/python3.11/asyncio/base_events.py", line 1936, in _run_once
  handle._run()
 File "/home/wa1ter/.local/share/uv/python/cpython-3.11.14-linux-x86_64-gnu/lib/python3.11/asyncio/events.py", line 84, in _run
  self._context.run(self._callback, *self._args)
 File "/home/wa1ter/ESG-sft/.venv/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 621, in shell_main
  await self.dispatch_shell(msg, subshell_id=subshell_id)
 File "/home/wa1ter/ESG-sft/.venv/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 478, in dispatch_shell
  await result
 File "/home/wa1ter/ESG-sft/.venv/lib/python3.11/site-packages/ipykernel/ipkernel.py", line 372, in execute_request
  await super().execute_request(stream, ident, parent)
 File "/home/wa1ter/ESG-sft/.venv/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 834, in execute_request
  reply_content = await reply_content
 File "/home/wa1ter/ESG-sft/.venv/lib/python3.11/site-packages/ipykernel/ipkernel.py", line 464, in do_execute
  res = shell.run_cell(
 File "/home/wa1ter/ESG-sft/.venv/lib/python3.11/site-packages/ipykernel/zmqshell.py", line 663, in run_cell
  return super().run_cell(*args, **kwargs)
 File "/home/wa1ter/ESG-sft/.venv/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3123, in run_cell
  result = self._run_cell(
 File "/home/wa1ter/ESG-sft/.venv/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3178, in _run_cell
  result = runner(coro)
 File "/home/wa1ter/ESG-sft/.venv/lib/python3.11/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner
  coro.send(None)
 File "/home/wa1ter/ESG-sft/.venv/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3400, in run_cell_async
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
 File "/home/wa1ter/ESG-sft/.venv/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3641, in run_ast_nodes
  if await self.run_code(code, result, async_=asy):
 File "/home/wa1ter/ESG-sft/.venv/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3701, in run_code
  exec(code_obj, self.user_global_ns, self.user_ns)
 File "/tmp/ipykernel_88333/766085005.py", line 125, in <module>
  outputs = model.generate(
 File "/home/wa1ter/ESG-sft/.venv/lib/python3.11/site-packages/peft/peft_model.py", line 2048, in generate
  outputs = self.base_model.generate(*args, **kwargs)
 File "/home/wa1ter/ESG-sft/.venv/lib/python3.11/site-packages/unsloth/models/llama.py", line 2128, in unsloth_fast_generate
  output = self._old_generate(*args, **kwargs)
 File "/home/wa1ter/ESG-sft/.venv/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 120, in decorate_context
  return func(*args, **kwargs)
 File "/home/wa1ter/ESG-sft/.venv/lib/python3.11/site-packages/transformers/generation/utils.py", line 2668, in generate
  result = decoding_method(
 File "/home/wa1ter/ESG-sft/.venv/lib/python3.11/site-packages/transformers/generation/utils.py", line 2863, in _sample
  outputs = self._prefill(input_ids, generation_config, model_kwargs)
 File "/home/wa1ter/ESG-sft/.venv/lib/python3.11/site-packages/transformers/generation/utils.py", line 3857, in _prefill
  return self(**model_inputs, return_dict=True)
 File "/home/wa1ter/ESG-sft/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1775, in _wrapped_call_impl
  return self._call_impl(*args, **kwargs)
 File "/home/wa1ter/ESG-sft/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1786, in _call_impl
  return forward_call(*args, **kwargs)
 File "/home/wa1ter/ESG-sft/.venv/lib/python3.11/site-packages/unsloth/models/llama.py", line 1474, in _CausalLM_fast_forward
  outputs = self.model(
 File "/home/wa1ter/ESG-sft/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1775, in _wrapped_call_impl
  return self._call_impl(*args, **kwargs)
 File "/home/wa1ter/ESG-sft/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1786, in _call_impl
  return forward_call(*args, **kwargs)
 File "/home/wa1ter/ESG-sft/.venv/lib/python3.11/site-packages/unsloth/models/llama.py", line 1058, in LlamaModel_fast_forward
  attention_mask = _prepare_4d_causal_attention_mask_for_sdpa(
 File "/home/wa1ter/ESG-sft/.venv/lib/python3.11/site-packages/transformers/modeling_attn_mask_utils.py", line 394, in _prepare_4d_causal_attention_mask_for_sdpa
  attn_mask_converter = AttentionMaskConverter(is_causal=True, sliding_window=sliding_window)
 File "/home/wa1ter/ESG-sft/.venv/lib/python3.11/site-packages/transformers/modeling_attn_mask_utils.py", line 74, in __init__
  logger.warning_once(DEPRECATION_MESSAGE, FutureWarning)
 File "/home/wa1ter/ESG-sft/.venv/lib/python3.11/site-packages/transformers/utils/logging.py", line 327, in warning_once
  self.warning(*args, **kwargs)
Message: 'The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.'
Arguments: (<class 'FutureWarning'>,)
Evaluating:  0%|     | 1/200 [00:00<01:05, 3.05it/s]

RAW OUTPUT: 'Non-ESG'
PARSED PRED: Non-ESG
GT: Non-ESG
--------------------------------------------------------------------------------

Evaluating:  1%|     | 2/200 [00:00<00:55, 3.56it/s]

RAW OUTPUT: 'Non-ESG'
PARSED PRED: Non-ESG
GT: Non-ESG
--------------------------------------------------------------------------------

Evaluating:  2%|▏     | 3/200 [00:00<00:49, 3.98it/s]

RAW OUTPUT: 'Product Liability'
PARSED PRED: Product Liability
GT: Product Liability
--------------------------------------------------------------------------------

Evaluating:  2%|▏     | 4/200 [00:01<00:46, 4.19it/s]

RAW OUTPUT: 'Product Liability'
PARSED PRED: Product Liability
GT: Product Liability
--------------------------------------------------------------------------------

Evaluating:  2%|▎     | 5/200 [00:01<00:45, 4.32it/s]

RAW OUTPUT: 'Product Liability'
PARSED PRED: Product Liability
GT: Product Liability
--------------------------------------------------------------------------------

Evaluating: 100%|██████████| 200/200 [00:48<00:00, 4.11it/s]

=== Evaluation Summary ===
Total evaluated samples: 200
Parseable predictions:  199
Failed predictions:   1
Parse failure rate:   0.0050

======================================================================
PARSEABLE-ONLY METRICS
======================================================================
Accuracy:      0.7739
Macro Precision:   0.5972
Macro Recall:    0.3291
Macro F1:      0.3949
Weighted Precision: 0.7814
Weighted Recall:   0.7739
Weighted F1:     0.7363

=== Classification Report (Parseable-only) ===
             precision  recall f1-score  support

     Climate Change    1.00   0.33   0.50     6
     Natural Capital    0.00   0.00   0.00     0
    Pollution & Waste    0.00   0.00   0.00     6
      Human Capital    0.86   0.43   0.57    14
    Product Liability    0.94   0.58   0.71    26
   Community Relations    0.00   0.00   0.00     0
  Corporate Governance    0.83   0.42   0.56    12
Business Ethics & Values    1.00   0.22   0.36     9
         Non-ESG    0.75   0.98   0.85    126

        accuracy              0.77    199
        macro avg    0.60   0.33   0.39    199
      weighted avg    0.78   0.77   0.74    199

,Climate Change,Natural Capital,Pollution & Waste,Human Capital,Product Liability,Community Relations,Corporate Governance,Business Ethics & Values,Non-ESG
Climate Change,2,0,0,0,0,0,0,0,4
Natural Capital,0,0,0,0,0,0,0,0,0
Pollution & Waste,0,0,0,0,0,0,0,0,6
Human Capital,0,0,0,6,0,0,0,0,8
Product Liability,0,0,0,0,15,0,0,0,11
Community Relations,0,0,0,0,0,0,0,0,0
Corporate Governance,0,0,0,0,0,0,5,0,7
Business Ethics & Values,0,0,0,0,0,0,1,2,6
Non-ESG,0,0,0,1,1,0,0,0,124

======================================================================
END-TO-END METRICS (failed outputs counted as wrong)
======================================================================
Accuracy:      0.7700
Macro Precision:   0.5972
Macro Recall:    0.3267
Macro F1:      0.3931
Weighted Precision: 0.7822
Weighted Recall:   0.7700
Weighted F1:     0.7340

=== Classification Report (End-to-end) ===
             precision  recall f1-score  support

     Climate Change    1.00   0.33   0.50     6
     Natural Capital    0.00   0.00   0.00     0
    Pollution & Waste    0.00   0.00   0.00     6
      Human Capital    0.86   0.43   0.57    14
    Product Liability    0.94   0.56   0.70    27
   Community Relations    0.00   0.00   0.00     0
  Corporate Governance    0.83   0.42   0.56    12
Business Ethics & Values    1.00   0.22   0.36     9
         Non-ESG    0.75   0.98   0.85    126

        micro avg    0.77   0.77   0.77    200
        macro avg    0.60   0.33   0.39    200
      weighted avg    0.78   0.77   0.73    200


=== Confusion Matrix (End-to-end) ===
Rows = ground truth, Columns = prediction

,Climate Change,Natural Capital,Pollution & Waste,Human Capital,Product Liability,Community Relations,Corporate Governance,Business Ethics & Values,Non-ESG,__INVALID__
Climate Change,2,0,0,0,0,0,0,0,4,0
Natural Capital,0,0,0,0,0,0,0,0,0,0
Pollution & Waste,0,0,0,0,0,0,0,0,6,0
Human Capital,0,0,0,6,0,0,0,0,8,0
Product Liability,0,0,0,0,15,0,0,0,11,1
Community Relations,0,0,0,0,0,0,0,0,0,0
Corporate Governance,0,0,0,0,0,0,5,0,7,0
Business Ethics & Values,0,0,0,0,0,0,1,2,6,0
Non-ESG,0,0,0,1,1,0,0,0,124,0
__INVALID__,0,0,0,0,0,0,0,0,0,0

Invalid prediction count: 1

=== Failed Cases by Reason ===

          reason count
0 prediction_parse_failed   1

=== Failed Cases (head 20) ===

,paragraph_id,reason,ground_truth,raw_output
0,PFG_2022_RISK_033,prediction_parse_failed,Product Liability,Regulatory Compliance

<a name="Save"></a>
### Saving, loading finetuned models
To save the final model as LoRA adapters, either use Hugging Face's `push_to_hub` for an online save or `save_pretrained` for a local save.

**[NOTE]** This ONLY saves the LoRA adapters, and not the full model. To save to 16bit or GGUF, scroll down!

In [20]:
model.save_pretrained("llama_lora") # Local saving
tokenizer.save_pretrained("llama_lora")
# model.push_to_hub("your_name/llama_lora", token = "YOUR_HF_TOKEN") # Online saving
# tokenizer.push_to_hub("your_name/llama_lora", token = "YOUR_HF_TOKEN") # Online saving

('llama_lora/tokenizer_config.json',
 'llama_lora/chat_template.jinja',
 'llama_lora/tokenizer.json')

Now if you want to load the LoRA adapters we just saved for inference, set `False` to `True`:

In [18]:
if True:
  from unsloth import FastLanguageModel
  model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "llama_lora", # YOUR MODEL YOU USED FOR TRAINING
    max_seq_length = max_seq_length,
    dtype = dtype,
    load_in_4bit = load_in_4bit,
  )
  FastLanguageModel.for_inference(model) # Enable native 2x faster inference

messages = [
  {"role": "user", "content": "Describe a tall tower in the capital of France."},
]
inputs = tokenizer.apply_chat_template(
  messages,
  tokenize = True,
  add_generation_prompt = True, # Must add for generation
  return_tensors = "pt",
).to("cuda")

from transformers import TextStreamer
text_streamer = TextStreamer(tokenizer, skip_prompt = True)
_ = model.generate(input_ids = inputs, streamer = text_streamer, max_new_tokens = 128,
          use_cache = True, temperature = 1.5, min_p = 0.1)

==((====))== Unsloth 2026.3.4: Fast Llama patching. Transformers: 5.2.0.
  \\  /|  NVIDIA GeForce RTX 4090. Num GPUs = 1. Max memory: 23.518 GB. Platform: Linux.
O^O/ \_/ \  Torch: 2.9.1+cu128. CUDA: 8.9. CUDA Toolkit: 12.8. Triton: 3.5.1
\    /  Bfloat16 = TRUE. FA [Xformers = 0.0.33.post2. FA2 = False]
 "-____-"   Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Loading weights: 100%|██████████| 254/254 [00:00<00:00, 760.87it/s, Materializing param=model.norm.weight]
Unsloth: Will load unsloth/llama-3.2-3b-instruct-unsloth-bnb-4bit as a legacy tokenizer.

The tower in question is likely the Eiffel Tower, which stands approximately 324 meters (1,063 feet) tall and is an iconic landmark in Paris, France's capital city. Completed in 1889 for the World's Fair, this iron lattice tower has become a symbol of Paris and one of the most recognizable structures in the world. Its four main pillars and four beams support a network of vertical beams that create a lattice pattern, giving the tower its distinctive appearance.<|eot_id|>

You can also use Hugging Face's `AutoPeftModelForCausalLM`. Only use this if you do not have `unsloth` installed. It can be hopelessly slow, since `4bit` model downloading is not supported, and Unsloth's **inference is 2x faster**.

In [ ]:
if False:
  # I highly do NOT suggest - use Unsloth if possible
  from peft import AutoPeftModelForCausalLM
  from transformers import AutoTokenizer
  model = AutoPeftModelForCausalLM.from_pretrained(
    "llama_lora", # YOUR MODEL YOU USED FOR TRAINING
    load_in_4bit = load_in_4bit,
  )
  tokenizer = AutoTokenizer.from_pretrained("llama_lora")

### Saving to float16 for VLLM

We also support saving to `float16` directly. Select `merged_16bit` for float16 or `merged_4bit` for int4. We also allow `lora` adapters as a fallback. Use `push_to_hub_merged` to upload to your Hugging Face account! You can go to https://huggingface.co/settings/tokens for your personal tokens. See [our docs](https://unsloth.ai/docs/basics/inference-and-deployment) for more deployment options.

In [ ]:
# Merge to 16bit
if False: model.save_pretrained_merged("llama_finetune_16bit", tokenizer, save_method = "merged_16bit",)
if False: model.push_to_hub_merged("HF_USERNAME/llama_finetune_16bit", tokenizer, save_method = "merged_16bit", token = "YOUR_HF_TOKEN")

# Merge to 4bit
if False: model.save_pretrained_merged("llama_finetune_4bit", tokenizer, save_method = "merged_4bit",)
if False: model.push_to_hub_merged("HF_USERNAME/llama_finetune_4bit", tokenizer, save_method = "merged_4bit", token = "YOUR_HF_TOKEN")

# Just LoRA adapters
if False:
  model.save_pretrained("llama_lora")
  tokenizer.save_pretrained("llama_lora")
if False:
  model.push_to_hub("HF_USERNAME/llama_lora", token = "YOUR_HF_TOKEN")
  tokenizer.push_to_hub("HF_USERNAME/llama_lora", token = "YOUR_HF_TOKEN")

### GGUF / llama.cpp Conversion
To save to `GGUF` / `llama.cpp`, we support it natively now! We clone `llama.cpp` and we default save it to `q8_0`. We allow all methods like `q4_k_m`. Use `save_pretrained_gguf` for local saving and `push_to_hub_gguf` for uploading to HF.

Some supported quant methods (full list on our [docs page](https://unsloth.ai/docs/basics/inference-and-deployment/saving-to-gguf)):
* `q8_0` - Fast conversion. High resource use, but generally acceptable.
* `q4_k_m` - Recommended. Uses Q6_K for half of the attention.wv and feed_forward.w2 tensors, else Q4_K.
* `q5_k_m` - Recommended. Uses Q6_K for half of the attention.wv and feed_forward.w2 tensors, else Q5_K.

[**NEW**] To finetune and auto export to Ollama, try our [Ollama notebook](https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/Llama3_(8B)-Ollama.ipynb)

In [ ]:
# Save to 8bit Q8_0
if False: model.save_pretrained_gguf("llama_finetune", tokenizer,)
# Remember to go to https://huggingface.co/settings/tokens for a token!
# And change hf to your username!
if False: model.push_to_hub_gguf("HF_USERNAME/llama_finetune", tokenizer, token = "YOUR_HF_TOKEN")

# Save to 16bit GGUF
if False: model.save_pretrained_gguf("llama_finetune", tokenizer, quantization_method = "f16")
if False: model.push_to_hub_gguf("HF_USERNAME/llama_finetune", tokenizer, quantization_method = "f16", token = "YOUR_HF_TOKEN")

# Save to q4_k_m GGUF
if False: model.save_pretrained_gguf("llama_finetune", tokenizer, quantization_method = "q4_k_m")
if False: model.push_to_hub_gguf("HF_USERNAME/llama_finetune", tokenizer, quantization_method = "q4_k_m", token = "YOUR_HF_TOKEN")

# Save to multiple GGUF options - much faster if you want multiple!
if False:
  model.push_to_hub_gguf(
    "HF_USERNAME/llama_finetune", # Change hf to your username!
    tokenizer,
    quantization_method = ["q4_k_m", "q8_0", "q5_k_m",],
    token = "YOUR_HF_TOKEN", # Get a token at https://huggingface.co/settings/tokens
  )

And we're done! If you have any questions on Unsloth, we have a [Discord](https://discord.gg/unsloth) channel! If you find any bugs or want to keep updated with the latest LLM stuff, or need help, join projects etc, feel free to join our Discord!

Some other resources:
1. Looking to use Unsloth locally? Read our [Installation Guide](https://unsloth.ai/docs/get-started/install) for details on installing Unsloth on Windows, Docker, AMD, Intel GPUs.
2. Learn how to do Reinforcement Learning with our [RL Guide and notebooks](https://unsloth.ai/docs/get-started/reinforcement-learning-rl-guide).
3. Read our guides and notebooks for [Text-to-speech (TTS)](https://unsloth.ai/docs/basics/text-to-speech-tts-fine-tuning) and [vision](https://unsloth.ai/docs/basics/vision-fine-tuning) model support.
4. Explore our [LLM Tutorials Directory](https://unsloth.ai/docs/models/tutorials-how-to-fine-tune-and-run-llms) to find dedicated guides for each model.
5. Need help with Inference? Read our [Inference & Deployment page](https://unsloth.ai/docs/basics/inference-and-deployment) for details on using vLLM, llama.cpp, Ollama etc.

<div class="align-center">
 <a href="https://unsloth.ai"><img src="https://github.com/unslothai/unsloth/raw/main/images/unsloth%20new%20logo.png" width="115"></a>
 <a href="https://discord.gg/unsloth"><img src="https://github.com/unslothai/unsloth/raw/main/images/Discord.png" width="145"></a>
 <a href="https://unsloth.ai/docs/"><img src="https://github.com/unslothai/unsloth/blob/main/images/documentation%20green%20button.png?raw=true" width="125"></a>

 Join Discord if you need help + ⭐️ <i>Star us on <a href="https://github.com/unslothai/unsloth">Github</a> </i> ⭐️

 <b>This notebook and all Unsloth notebooks are licensed [LGPL-3.0](https://github.com/unslothai/notebooks?tab=LGPL-3.0-1-ov-file#readme)</b>
</div>